export interface IColor {
  id: string;
  color: string;
  nameColorEnd: string;
  DMC: string;
  nameColorRu: string;
  count: number;
}

export const objectColor: IColor[] = [
  {
    id: crypto.randomUUID(),
    color: '#FFFFFF',
    DMC: 'blanc',
    nameColorEnd: 'White',
    nameColorRu: 'Белый',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#E9E9D4', DMC: 'Ecru', nameColorEnd: 'Ecru', nameColorRu: 'Кремовый', count: 0 },
  {
    id: crypto.randomUUID(),
    DMC: 'B5200',
    color: '#FFFFFF',
    nameColorEnd: 'Ultra white',
    nameColorRu: 'Белоснежный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9F3845',
    DMC: '150',
    nameColorEnd: 'Dusty Rose — ultra vy dk',
    nameColorRu: 'Пыльная роза, ультра очень тёмный (оч.т.)',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#F2BCC5',
    DMC: '151',
    nameColorEnd: 'Dusty Rose — vy lt',
    nameColorRu: 'Пыльная роза, очень светлый (оч.св.)',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#CFA296',
    DMC: '152',
    nameColorEnd: 'Shell Pink — med lt',
    nameColorRu: 'Розовых ракушек, средне светлый (ср.св.)',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#DEBCD9',
    DMC: '153',
    nameColorEnd: 'Violet — vy lt',
    nameColorRu: 'Фиолетовый, очень светлый (оч.св)',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4D2E3D',
    DMC: '154',
    nameColorEnd: 'Grape — vy dk',
    nameColorRu: 'Красного винограда, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#908BC3',
    DMC: '155',
    nameColorEnd: 'Blue Violet — med dk',
    nameColorRu: 'Сине-фиолетовый, ср.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8B9AC5',
    DMC: '156',
    nameColorEnd: 'Blue Violet — med lt',
    nameColorRu: 'Сине-фиолетовый, ср.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ABC2DE',
    DMC: '157',
    nameColorEnd: 'Cornflower Blue — vy lt',
    nameColorRu: 'Васильковый, кобальтовый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#465082',
    DMC: '158',
    nameColorEnd: 'Cornflower Blue-med vy dk',
    nameColorRu: 'Васильковый, кобальтовый, ср.оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#A7B4CD',
    DMC: '159',
    nameColorEnd: 'Gray Blue-lt',
    nameColorRu: 'Серо-синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8290AE',
    DMC: '160',
    nameColorEnd: 'Gray Blue-med',
    nameColorRu: 'Серо-синий, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#667594',
    DMC: '161',
    nameColorEnd: 'Gray Blue',
    nameColorRu: 'Серо-синий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#BDDBE6',
    DMC: '162',
    nameColorEnd: 'Blue-ultra vy lt',
    nameColorRu: 'Голубой, ультра оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#569571',
    DMC: '163',
    nameColorEnd: 'Celadon Green-med',
    nameColorRu: 'Серовато-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9FCC8D',
    DMC: '164',
    nameColorEnd: 'Forest Green-lt',
    nameColorRu: 'Зеленый лесной, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#DAD878',
    DMC: '165',
    nameColorEnd: 'Moss Green-vylt',
    nameColorRu: 'Мох, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#BFBB20',
    DMC: '166',
    nameColorEnd: 'Moss Green-med lt',
    nameColorRu: 'Мох, ср.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9F8447',
    DMC: '167',
    nameColorEnd: 'Yellow Beige-vy dk',
    nameColorRu: 'Желтовато-бежевый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#B4C3C1',
    DMC: '168',
    nameColorEnd: 'Pewter-vy lt',
    nameColorRu: 'Оловянный, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8B9A94',
    DMC: '169',
    nameColorEnd: 'Pewter-lt',
    nameColorRu: 'Оловянный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9870AC',
    DMC: '208',
    nameColorEnd: 'Lavender-vy dk',
    nameColorRu: 'Лаванда, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#B693B6',
    DMC: '209',
    nameColorEnd: 'Lavender-dk',
    nameColorRu: 'Лаванда, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#C9AFDD',
    DMC: '210',
    nameColorEnd: 'Lavender-med',
    nameColorRu: 'Лаванда, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#D4C3E4',
    DMC: '211',
    nameColorEnd: 'Lavender-lt',
    nameColorRu: 'Лаванда, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#884238',
    DMC: '221',
    nameColorEnd: 'Shel lPink-vy dk',
    nameColorRu: 'Розовых ракушек, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#BB817B',
    DMC: '223',
    nameColorEnd: 'Shell Pink-lt',
    nameColorRu: 'Розовых ракушек, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#DFB3A6',
    DMC: '224',
    nameColorEnd: 'ShellPink-vy lt',
    nameColorRu: 'Розовых ракушек, оч. св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#784E24',
    DMC: '225',
    nameColorEnd: 'ShellPink-ultra vy lt',
    nameColorRu: 'Розовых ракушек, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#784E24',
    DMC: '300',
    nameColorEnd: 'Mahogany-vy dk',
    nameColorRu: 'Красного дерева, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#AA6730',
    DMC: '301',
    nameColorEnd: 'Mahogany-med',
    nameColorRu: 'Красного дерева, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9E3332',
    DMC: '304',
    nameColorEnd: 'Christmas Red-med',
    nameColorRu: 'Рождественский красный, ср.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#F6E311', DMC: '307', nameColorEnd: 'Lemon', nameColorRu: 'Лимонный', count: 0 },
  { id: crypto.randomUUID(), color: '#B84351', DMC: '309', nameColorEnd: 'Rose-dk', nameColorRu: 'Розы, т.', count: 0 },
  { id: crypto.randomUUID(), color: '#000000', DMC: '310', nameColorEnd: 'Black', nameColorRu: 'Черный', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#30506F',
    DMC: '311',
    nameColorEnd: 'Navy Blue-med',
    nameColorRu: 'Темно-синий, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#386189',
    DMC: '312',
    nameColorEnd: 'Navy Blue-lt',
    nameColorRu: 'Темно-синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8E5D5C',
    DMC: '315',
    nameColorEnd: 'Antique Mauve-med dk',
    nameColorRu: 'Античный розовато-лиловый, ср.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#BF889C',
    DMC: '316',
    nameColorEnd: 'Antique Mauve-med',
    nameColorRu: 'Античный розовато-лиловый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#697275',
    DMC: '317',
    nameColorEnd: 'Pewter Grey',
    nameColorRu: 'Оловянносерый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#A0A7B0',
    DMC: '318',
    nameColorEnd: 'Steel Grey-lt',
    nameColorRu: 'Стальной, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#35633D',
    DMC: '319',
    nameColorEnd: 'Pistachio Green-vy dk',
    nameColorRu: 'Фисташково-зеленый,оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#71a072',
    DMC: '320',
    nameColorEnd: 'Pistachio Green-med',
    nameColorRu: 'Фисташково-зеленый,ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ce1f32',
    DMC: '321',
    nameColorEnd: 'Christmas Red',
    nameColorRu: 'Рождественскийкрасный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#647e9d',
    DMC: '322',
    nameColorEnd: 'NavyBlue-vy lt',
    nameColorRu: 'Темно-синий,оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a92332',
    DMC: '326',
    nameColorEnd: 'Rose-vy dk',
    nameColorRu: 'Розы,оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#723657',
    DMC: '327',
    nameColorEnd: 'Violet-vy dk',
    nameColorRu: 'Фиолетовый,оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6c5086',
    DMC: '333',
    nameColorEnd: 'BlueViolet-vy dk',
    nameColorRu: 'Сине-фиолетовый,оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4c698c',
    DMC: '334',
    nameColorEnd: 'BabyBlue-med',
    nameColorRu: 'Нежноголубой,ср.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#e56d7f', DMC: '335', nameColorEnd: 'Rose', nameColorRu: 'Розы', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#0c1225',
    DMC: '336',
    nameColorEnd: 'Navy Blue',
    nameColorRu: 'Темно-синий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9389c1',
    DMC: '340',
    nameColorEnd: 'Blue Violet-med',
    nameColorRu: 'Сине-фиолетовый,ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a2accd',
    DMC: '341',
    nameColorEnd: 'Blue Violet-lt',
    nameColorRu: 'Сине-фиолетовый,св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bf3e31',
    DMC: '347',
    nameColorEnd: 'Salmon — vy dk',
    nameColorRu: 'Лососевый,оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c24731',
    DMC: '349',
    nameColorEnd: 'Coral-dk',
    nameColorRu: 'Коралловокрасный,т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e46647',
    DMC: '350',
    nameColorEnd: 'Coral-med',
    nameColorRu: 'Кораллово красный,ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f78465',
    DMC: '351',
    nameColorEnd: 'Coral',
    nameColorRu: 'Кораллово красный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f69d80',
    DMC: '352',
    nameColorEnd: 'Coral-lt',
    nameColorRu: 'Коралловокрасный,св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#fdbca1', DMC: '353', nameColorEnd: 'Peach', nameColorRu: 'Персиковый', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#9a3b2d',
    DMC: '355',
    nameColorEnd: 'TerraCotta-dk',
    nameColorRu: 'Терракотовый,т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a06757',
    DMC: '356',
    nameColorEnd: 'TerraCotta-med',
    nameColorRu: 'Терракотовый,ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4c7047',
    DMC: '367',
    nameColorEnd: 'PistachioGreen-dk',
    nameColorRu: 'Фисташково-зеленый,т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#91ab84',
    DMC: '368',
    nameColorEnd: 'PistachioGreen-lt',
    nameColorRu: 'Фисташково-зеленый,св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ccdcbe',
    DMC: '369',
    nameColorEnd: 'PistachioGreen-vy lt',
    nameColorRu: 'Фисташково-зеленый,оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bbaa55',
    DMC: '370',
    nameColorEnd: 'Mustard-med',
    nameColorRu: 'Горчичный,ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a08f4d',
    DMC: '371',
    nameColorEnd: 'Mustard',
    nameColorRu: 'Горчичный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9c8c4a',
    DMC: '372',
    nameColorEnd: 'Mustard — lt',
    nameColorRu: 'Горчичный,св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#934d29',
    DMC: '400',
    nameColorEnd: 'Mahogany — dk',
    nameColorRu: 'Красного дерева, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e8a76d',
    DMC: '402',
    nameColorEnd: 'Mahogany — vy lt',
    nameColorRu: 'Красного дерева, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c49a87',
    DMC: '407',
    nameColorEnd: 'Desert Sand — dk',
    nameColorRu: 'Пустынного песка, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#535657',
    DMC: '413',
    nameColorEnd: 'Pewter Grey — dk',
    nameColorRu: 'Оловянно серый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#95909d',
    DMC: '414',
    nameColorEnd: 'Steel Grey — dk',
    nameColorRu: 'Стальной, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d3d4db',
    DMC: '415',
    nameColorEnd: 'Pearl Grey',
    nameColorRu: 'Жемчужно серый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#866226',
    DMC: '420',
    nameColorEnd: 'Hazelnut Brown — dk',
    nameColorRu: 'Фундука, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d0ba79',
    DMC: '422',
    nameColorEnd: 'Hazelnut Brown — lt',
    nameColorRu: 'Фундука, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#775437',
    DMC: '433',
    nameColorEnd: 'Brown — med',
    nameColorRu: 'Коричневый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b78237',
    DMC: '434',
    nameColorEnd: 'Brown — lt',
    nameColorRu: 'Коричневый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c4863a',
    DMC: '435',
    nameColorEnd: 'Brown — vy lt',
    nameColorRu: 'Коричневый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c09557',
    DMC: '436',
    nameColorEnd: 'Tan',
    nameColorRu: 'Желто-коричневый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d9b879',
    DMC: '437',
    nameColorEnd: 'Tan — lt',
    nameColorRu: 'Желто-коричневый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f5d500',
    DMC: '444',
    nameColorEnd: 'Lemon — dk',
    nameColorRu: 'Лимонный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f0ed85',
    DMC: '445',
    nameColorEnd: 'Lemon — lt',
    nameColorRu: 'Лимонный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#978b81',
    DMC: '451',
    nameColorEnd: 'Shell Grey — dk',
    nameColorRu: 'Серых ракушек, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bbaea6',
    DMC: '452',
    nameColorEnd: 'Shell Grey — med',
    nameColorRu: 'Серых ракушек, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e3dcdb',
    DMC: '453',
    nameColorEnd: 'Shell Grey — lt',
    nameColorRu: 'Серых ракушек, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#798738',
    DMC: '469',
    nameColorEnd: 'Avocado Green',
    nameColorRu: 'Авокадо',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#98a859',
    DMC: '470',
    nameColorEnd: 'Avocado Green — lt',
    nameColorRu: 'Авокадо, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#929937',
    DMC: '471',
    nameColorEnd: 'Avocado Green — vy lt',
    nameColorRu: 'Авокадо, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#dee077',
    DMC: '472',
    nameColorEnd: 'Avocado Green — ultra lt',
    nameColorRu: 'Авокадо, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#98232c',
    DMC: '498',
    nameColorEnd: 'Christmas Red — dk',
    nameColorRu: 'Рождественский красный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#14361e',
    DMC: '500',
    nameColorEnd: 'Blue Green — vy dk',
    nameColorRu: 'Сине-зеленый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#496f5c',
    DMC: '501',
    nameColorEnd: 'Blue Green — dk',
    nameColorRu: 'Сине-зеленый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#799a83',
    DMC: '502',
    nameColorEnd: 'Blue Green',
    nameColorRu: 'Сине-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8ebea9',
    DMC: '503',
    nameColorEnd: 'Blue Green — med',
    nameColorRu: 'Сине-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d1e2d7',
    DMC: '504',
    nameColorEnd: 'Blue Green — vy lt',
    nameColorRu: 'Сине-зеленый, оч.св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#418253', DMC: '505', nameColorEnd: 'Jade', nameColorRu: 'Нефрит', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#166d92',
    DMC: '517',
    nameColorEnd: 'Wedgwood — dk',
    nameColorRu: 'Пыльно-синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6b9cb9',
    DMC: '518',
    nameColorEnd: 'Wedgwood — lt',
    nameColorRu: 'Пыльно-синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a8c6d8',
    DMC: '519',
    nameColorEnd: 'Sky Blue',
    nameColorRu: 'Небесно голубой',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4f6035',
    DMC: '520',
    nameColorEnd: 'Fern Green — dk',
    nameColorRu: 'Папоротниковый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#93a181',
    DMC: '522',
    nameColorEnd: 'Fern Green',
    nameColorRu: 'Папоротниковый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a5a888',
    DMC: '523',
    nameColorEnd: 'Fern Green — lt',
    nameColorRu: 'Папоротниковый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bec0a8',
    DMC: '524',
    nameColorEnd: 'Fern Green — vy lt',
    nameColorRu: 'Папоротниковый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#504f50',
    DMC: '535',
    nameColorEnd: 'Ash Grey — vy lt',
    nameColorRu: 'Пепельный, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f0e3d4',
    DMC: '543',
    nameColorEnd: 'Beige Brown — ultra vy lt',
    nameColorRu: 'Бежево-коричневый, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#541244',
    DMC: '550',
    nameColorEnd: 'Violet — vy dk',
    nameColorRu: 'Фиолетовый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#7b3f6c',
    DMC: '552',
    nameColorEnd: 'Violet — med',
    nameColorRu: 'Фиолетовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a772a4',
    DMC: '553',
    nameColorEnd: 'Violet',
    nameColorRu: 'Фиолетовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ae99b1',
    DMC: '554',
    nameColorEnd: 'Violet — lt',
    nameColorRu: 'Фиолетовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#377557',
    DMC: '561',
    nameColorEnd: 'Jade — vy dk',
    nameColorRu: 'Нефрит, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#599b6d',
    DMC: '562',
    nameColorEnd: 'Jade — med',
    nameColorRu: 'Нефрит, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#87c39e',
    DMC: '563',
    nameColorEnd: 'Jade — lt',
    nameColorRu: 'Нефрит, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9cd0ab',
    DMC: '564',
    nameColorEnd: 'Jade — vy lt',
    nameColorRu: 'Нефрит, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#68772d',
    DMC: '580',
    nameColorEnd: 'Moss Green — dk',
    nameColorRu: 'Мох, т.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#9fa146', DMC: '581', nameColorEnd: 'Moss Green', nameColorRu: 'Мох', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#70aeb4',
    DMC: '597',
    nameColorEnd: 'Turquoise',
    nameColorRu: 'Бирюзовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#97ccca',
    DMC: '598',
    nameColorEnd: 'Turquoise — lt',
    nameColorRu: 'Бирюзовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bf1c48',
    DMC: '600',
    nameColorEnd: 'Cranberry — vy dk',
    nameColorRu: 'Клюквенный, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d34067',
    DMC: '601',
    nameColorEnd: 'Cranberry — dk',
    nameColorRu: 'Клюквенный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ca0b51',
    DMC: '602',
    nameColorEnd: 'Cranberry — med',
    nameColorRu: 'Клюквенный, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ef7ba1',
    DMC: '603',
    nameColorEnd: 'Cranberry',
    nameColorRu: 'Клюквенный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ec9ab9',
    DMC: '604',
    nameColorEnd: 'Cranberry — lt',
    nameColorRu: 'Клюквенный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#faccdb',
    DMC: '605',
    nameColorEnd: 'Cranberry — vy lt',
    nameColorRu: 'Клюквенный, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ea592c',
    DMC: '606',
    nameColorEnd: 'Bright Orange Red',
    nameColorRu: 'Яркий красно-оранжевый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f06e46',
    DMC: '608',
    nameColorEnd: 'Bright Orange',
    nameColorRu: 'Ярко оранжевый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#806638',
    DMC: '610',
    nameColorEnd: 'Drab Brown — vy dk',
    nameColorRu: 'Тускло-коричневый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9e9072',
    DMC: '611',
    nameColorEnd: 'Drab Brown — dk',
    nameColorRu: 'Тускло-коричневый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#917d4a',
    DMC: '612',
    nameColorEnd: 'Drab Brown — med',
    nameColorRu: 'Тускло-коричневый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bcae83',
    DMC: '613',
    nameColorEnd: 'Drab Brown — lt',
    nameColorRu: 'Тускло-коричневый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8c593e',
    DMC: '632',
    nameColorEnd: 'Desert Sand — ultra vy dk',
    nameColorRu: 'Пустынного песка, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#938962',
    DMC: '640',
    nameColorEnd: 'Beige Grey — vy dk',
    nameColorRu: 'Бежево-серый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bab599',
    DMC: '642',
    nameColorEnd: 'Beige Grey — dk',
    nameColorRu: 'Бежево-серый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d6d3c1',
    DMC: '644',
    nameColorEnd: 'Beige Grey — med',
    nameColorRu: 'Бежево-серый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#747e65',
    DMC: '645',
    nameColorEnd: 'Beaver Grey — vy dk',
    nameColorRu: 'Боброво-серый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#97978e',
    DMC: '646',
    nameColorEnd: 'Beaver Grey — dk',
    nameColorRu: 'Боброво-серый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#abafa3',
    DMC: '647',
    nameColorEnd: 'Beaver Grey — med',
    nameColorRu: 'Боброво-серый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#babfad',
    DMC: '648',
    nameColorEnd: 'Beaver Grey — lt',
    nameColorRu: 'Боброво-серый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d12627',
    DMC: '666',
    nameColorEnd: 'Christmas Red — bright',
    nameColorRu: 'Рождественский красный, яркий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#eed7a1',
    DMC: '676',
    nameColorEnd: 'Old Gold — lt',
    nameColorRu: 'Старого золота, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ede0ba',
    DMC: '677',
    nameColorEnd: 'Old Gold — vy lt',
    nameColorRu: 'Старого золота, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#af8334',
    DMC: '680',
    nameColorEnd: 'Old Gold — dk',
    nameColorRu: 'Старого золота, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#015731',
    DMC: '699',
    nameColorEnd: 'Christmas Green',
    nameColorRu: 'Рождественский зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#2e9148',
    DMC: '700',
    nameColorEnd: 'Christmas Green — bright',
    nameColorRu: 'Рождественский зеленый, яркий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#007a3f',
    DMC: '701',
    nameColorEnd: 'Christmas Green — lt',
    nameColorRu: 'Рождественский зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#59a052',
    DMC: '702',
    nameColorEnd: 'Kelly Green',
    nameColorRu: 'Мутновато-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#81b85e',
    DMC: '703',
    nameColorEnd: 'Chartreuse',
    nameColorRu: 'Бледно-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bad765',
    DMC: '704',
    nameColorEnd: 'Chartreuse — bright',
    nameColorRu: 'Бледно-зеленый, яркий',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#e1e1d9', DMC: '712', nameColorEnd: 'Cream', nameColorRu: 'Кремовый', count: 0 },
  { id: crypto.randomUUID(), color: '#9f2d6f', DMC: '718', nameColorEnd: 'Plum', nameColorRu: 'Сливовый', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#ec6810',
    DMC: '720',
    nameColorEnd: 'Orange Spice — dk',
    nameColorRu: 'Красновато-рыжеватый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e4752b',
    DMC: '721',
    nameColorEnd: 'Orange Spice — med',
    nameColorRu: 'Красновато-рыжеватый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#faa463',
    DMC: '722',
    nameColorEnd: 'Orange Spice — lt',
    nameColorRu: 'Красновато-рыжеватый, св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#fad558', DMC: '725', nameColorEnd: 'Topaz', nameColorRu: 'Топаз', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#ffe35f',
    DMC: '726',
    nameColorEnd: 'Topaz — lt',
    nameColorRu: 'Топаз, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#feee89',
    DMC: '727',
    nameColorEnd: 'Topaz — vy lt',
    nameColorRu: 'Топаз, оч.св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#ecbf3b', DMC: '728', nameColorEnd: 'Topaz', nameColorRu: 'Топаз', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#cc993d',
    DMC: '729',
    nameColorEnd: 'Old Gold — med',
    nameColorRu: 'Старого золота, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#746d2b',
    DMC: '730',
    nameColorEnd: 'Olive Green — vy dk',
    nameColorRu: 'Оливково-зеленый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#837d2f',
    DMC: '731',
    nameColorEnd: 'Olive Green — dk',
    nameColorRu: 'Оливково-зеленый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#91852a',
    DMC: '732',
    nameColorEnd: 'Olive Green',
    nameColorRu: 'Оливково-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a6a036',
    DMC: '733',
    nameColorEnd: 'Olive Green — med',
    nameColorRu: 'Оливково-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d1c66d',
    DMC: '734',
    nameColorEnd: 'Olive Green — lt',
    nameColorRu: 'Оливково-зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d9c38f',
    DMC: '738',
    nameColorEnd: 'Tan — vy lt',
    nameColorRu: 'Желто-коричневый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e5dab2',
    DMC: '739',
    nameColorEnd: 'Tan — ultra vy lt',
    nameColorRu: 'Желто-коричневый, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ff7600',
    DMC: '740',
    nameColorEnd: 'Tangerine',
    nameColorRu: 'Мандариновый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f69726',
    DMC: '741',
    nameColorEnd: 'Tangerine — med',
    nameColorRu: 'Мандариновый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ffc33a',
    DMC: '742',
    nameColorEnd: 'Tangerine — lt',
    nameColorRu: 'Мандариновый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ffda5a',
    DMC: '743',
    nameColorEnd: 'Yellow — med',
    nameColorRu: 'Желтый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ffe276',
    DMC: '744',
    nameColorEnd: 'Yellow — pale',
    nameColorRu: 'Желтый, бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ffeda9',
    DMC: '745',
    nameColorEnd: 'Yellow — lt pale',
    nameColorRu: 'Желтый, бледно св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f5f0df',
    DMC: '746',
    nameColorEnd: 'Off White',
    nameColorRu: 'Белесый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d3e9e7',
    DMC: '747',
    nameColorEnd: 'Sky Blue — vy lt',
    nameColorRu: 'Небесно голубой, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#efc1aa',
    DMC: '754',
    nameColorEnd: 'Peach — lt',
    nameColorRu: 'Персиковый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#eac0b4',
    DMC: '758',
    nameColorEnd: 'Terra Cotta — vy lt',
    nameColorRu: 'Терракотовый, оч.св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#e29690', DMC: '760', nameColorEnd: 'Salmon', nameColorRu: 'Лососевый', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#f4c4c1',
    DMC: '761',
    nameColorEnd: 'Salmon — lt',
    nameColorRu: 'Лососевый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e9e9eb',
    DMC: '762',
    nameColorEnd: 'Pearl Grey — vy lt',
    nameColorRu: 'Жемчужно серый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f3f6d4',
    DMC: '772',
    nameColorEnd: 'Yellow Green — vy lt',
    nameColorRu: 'Желто-зеленый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ceddea',
    DMC: '775',
    nameColorEnd: 'Baby Blue — vy lt',
    nameColorRu: 'Нежно голубой, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#eeaeb0',
    DMC: '776',
    nameColorEnd: 'Pink — med',
    nameColorRu: 'Розовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8a373b',
    DMC: '777',
    nameColorEnd: 'Raspberry — vy dk',
    nameColorRu: 'Малина оч.т',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ddb3b1',
    DMC: '778',
    nameColorEnd: 'Antique Mauve — vy lt',
    nameColorRu: 'Античный розовато-лиловый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6d5748',
    DMC: '779',
    nameColorEnd: 'Cocoa — dk',
    nameColorRu: 'Какао т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#936626',
    DMC: '780',
    nameColorEnd: 'Topaz — ultra vy dk',
    nameColorRu: 'Топаз, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ba8225',
    DMC: '781',
    nameColorEnd: 'Topaz — vy dk',
    nameColorRu: 'Топаз, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b38132',
    DMC: '782',
    nameColorEnd: 'Topaz — dk',
    nameColorRu: 'Топаз, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d19d2f',
    DMC: '783',
    nameColorEnd: 'Topaz — med',
    nameColorRu: 'Топаз, ср.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#161151',
    DMC: '791',
    nameColorEnd: 'Cornflower Blue — vy dk',
    nameColorRu: 'Васильковый, кобальтовый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#7971a0',
    DMC: '792',
    nameColorEnd: 'Cornflower Blue — dk',
    nameColorRu: 'Васильковый, кобальтовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#686d8d',
    DMC: '793',
    nameColorEnd: 'Cornflower Blue — med',
    nameColorRu: 'Васильковый, кобальтовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8ea7c0',
    DMC: '794',
    nameColorEnd: 'Cornflower Blue — lt',
    nameColorRu: 'Васильковый, кобальтовый, св.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#181f66',
    DMC: '796',
    nameColorEnd: 'Royal Blue — dk',
    nameColorRu: 'Чисто синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#2c4180',
    DMC: '797',
    nameColorEnd: 'Royal Blue',
    nameColorRu: 'Чисто синий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#445997',
    DMC: '798',
    nameColorEnd: 'Delft — dk',
    nameColorRu: 'Фарфоровый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6e8db5',
    DMC: '799',
    nameColorEnd: 'Delft — med',
    nameColorRu: 'Фарфоровый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c1d3df',
    DMC: '800',
    nameColorEnd: 'Delft — pale',
    nameColorRu: 'Фарфоровый, бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#63461f',
    DMC: '801',
    nameColorEnd: 'Coffee Brown — dk',
    nameColorRu: 'Кофейный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#437490',
    DMC: '806',
    nameColorEnd: 'Peacock Blue — dk',
    nameColorRu: 'Переливчатый синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#70a8b3',
    DMC: '807',
    nameColorEnd: 'Peacock Blue',
    nameColorRu: 'Переливчатый синий',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#6c91c0', DMC: '809', nameColorEnd: 'Delft', nameColorRu: 'Фарфоровый', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#91b4ce',
    DMC: '813',
    nameColorEnd: 'Blue — lt',
    nameColorRu: 'Синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#711f2e',
    DMC: '814',
    nameColorEnd: 'Garnet — dk',
    nameColorRu: 'Гранатовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9d3030',
    DMC: '815',
    nameColorEnd: 'Garnet — med',
    nameColorRu: 'Гранатовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#811024',
    DMC: '816',
    nameColorEnd: 'Garnet',
    nameColorRu: 'Гранатовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bd2e2e',
    DMC: '817',
    nameColorEnd: 'Coral Red — vy dk',
    nameColorRu: 'Кораллово красный, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f9d6dd',
    DMC: '818',
    nameColorEnd: 'Baby Pink',
    nameColorRu: 'Нежно розовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fbe2df',
    DMC: '819',
    nameColorEnd: 'Baby Pink — lt',
    nameColorRu: 'Нежно розовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#190f60',
    DMC: '820',
    nameColorEnd: 'Royal Blue — vy dk',
    nameColorRu: 'Чисто синий, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e2dfd3',
    DMC: '822',
    nameColorEnd: 'Beige Grey — lt',
    nameColorRu: 'Бежево-серый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#124477',
    DMC: '823',
    nameColorEnd: 'Navy Blue — dk',
    nameColorRu: 'Темно-синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#3b6292',
    DMC: '824',
    nameColorEnd: 'Blue — vy dk',
    nameColorRu: 'Синий, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#366390',
    DMC: '825',
    nameColorEnd: 'Blue — dk',
    nameColorRu: 'Синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#5a82a2',
    DMC: '826',
    nameColorEnd: 'Blue — med',
    nameColorRu: 'Синий, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b4d3e3',
    DMC: '827',
    nameColorEnd: 'Blue — vy lt',
    nameColorRu: 'Синий, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#cae2eb',
    DMC: '828',
    nameColorEnd: 'Blue — ultra vy lt',
    nameColorRu: 'Синий, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6f5422',
    DMC: '829',
    nameColorEnd: 'Golden Olive — vy dk',
    nameColorRu: 'Оливково-золотой, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#806c26',
    DMC: '830',
    nameColorEnd: 'Golden Olive — dk',
    nameColorRu: 'Оливково-золотой, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#957b2f',
    DMC: '831',
    nameColorEnd: 'Golden Olive — med',
    nameColorRu: 'Оливково-золотой, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b19a3f',
    DMC: '832',
    nameColorEnd: 'Golden Olive',
    nameColorRu: 'Оливково-золотой',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bfa43a',
    DMC: '833',
    nameColorEnd: 'Golden Olive — lt',
    nameColorRu: 'Оливково-золотой, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#cab751',
    DMC: '834',
    nameColorEnd: 'Golden Olive — vy lt',
    nameColorRu: 'Оливково-золотой, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#573c2a',
    DMC: '838',
    nameColorEnd: 'Beige Brown — vy dk',
    nameColorRu: 'Бежево-коричневый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#684e37',
    DMC: '839',
    nameColorEnd: 'Beige Brown — dk',
    nameColorRu: 'Бежево-коричневый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#977e65',
    DMC: '840',
    nameColorEnd: 'Beige Brown — med',
    nameColorRu: 'Бежево-коричневый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b39f8c',
    DMC: '841',
    nameColorEnd: 'Beige Brown — lt',
    nameColorRu: 'Бежево-коричневый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#cdb9a4',
    DMC: '842',
    nameColorEnd: 'Beige Brown — vy lt',
    nameColorRu: 'Бежево-коричневый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6c6e58',
    DMC: '844',
    nameColorEnd: 'Beaver Grey — ultra dk',
    nameColorRu: 'Боброво-серый, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#775820',
    DMC: '869',
    nameColorEnd: 'Hazelnut Brown — vy dk',
    nameColorRu: 'Фундука, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#043810',
    DMC: '890',
    nameColorEnd: 'Pistachio Green — ultra dk',
    nameColorRu: 'Фисташково зеленый, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ef4949',
    DMC: '891',
    nameColorEnd: 'Carnation — dk',
    nameColorRu: 'Гвоздичный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f85b64',
    DMC: '892',
    nameColorEnd: 'Carnation — med',
    nameColorRu: 'Гвоздичный, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fc6a84',
    DMC: '893',
    nameColorEnd: 'Carnation — lt',
    nameColorRu: 'Гвоздичный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f999a5',
    DMC: '894',
    nameColorEnd: 'Carnation — vy lt',
    nameColorRu: 'Гвоздичный, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#29542f',
    DMC: '895',
    nameColorEnd: 'Hunter Green — vy dk',
    nameColorRu: 'Защитный, грязновато зеленый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#502f1b',
    DMC: '898',
    nameColorEnd: 'Coffee Brown — vy dk',
    nameColorRu: 'Кофейный, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ee8593',
    DMC: '899',
    nameColorEnd: 'Rose — med',
    nameColorRu: 'Розы, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d45d28',
    DMC: '900',
    nameColorEnd: 'Burnt Orange — dk',
    nameColorRu: 'Оранжево-жженный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6b3b33',
    DMC: '902',
    nameColorEnd: 'Garnet — vy dk',
    nameColorRu: 'Гранатовый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4f6c33',
    DMC: '904',
    nameColorEnd: 'Parrot Green — vy dk',
    nameColorRu: 'Зеленый попугаевый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#759a3e',
    DMC: '905',
    nameColorEnd: 'Parrot Green — dk',
    nameColorRu: 'Зеленый попугаевый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#82ae44',
    DMC: '906',
    nameColorEnd: 'Parrot Green — med',
    nameColorRu: 'Зеленый попугаевый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a9c33e',
    DMC: '907',
    nameColorEnd: 'Parrot Green — lt',
    nameColorRu: 'Зеленый попугаевый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#00793b',
    DMC: '909',
    nameColorEnd: 'Emerald Green — vy dk',
    nameColorRu: 'Изумрудный, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#008c4c',
    DMC: '910',
    nameColorEnd: 'Emerald Green — dk',
    nameColorRu: 'Изумрудный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#40a756',
    DMC: '911',
    nameColorEnd: 'Emerald Green — med',
    nameColorRu: 'Изумрудный, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#58a96b',
    DMC: '912',
    nameColorEnd: 'Emerald Green — lt',
    nameColorRu: 'Изумрудный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#88c78d',
    DMC: '913',
    nameColorEnd: 'Nile Green — med',
    nameColorRu: 'Мутно-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#800137',
    DMC: '915',
    nameColorEnd: 'Plum — dk',
    nameColorRu: 'Сливовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#832a58',
    DMC: '917',
    nameColorEnd: 'Plum — med',
    nameColorRu: 'Сливовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8c3b1a',
    DMC: '918',
    nameColorEnd: 'Red Copper — dk',
    nameColorRu: 'Красной меди, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9b3b1b',
    DMC: '919',
    nameColorEnd: 'Red Copper',
    nameColorRu: 'Красной меди',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a74f2a',
    DMC: '920',
    nameColorEnd: 'Copper — med',
    nameColorRu: 'Медный, ср.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#c36b29', DMC: '921', nameColorEnd: 'Copper', nameColorRu: 'Медный', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#d6834d',
    DMC: '922',
    nameColorEnd: 'Copper — lt',
    nameColorRu: 'Медный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#42605c',
    DMC: '924',
    nameColorEnd: 'Grey Green — vy dk',
    nameColorRu: 'Серо-зеленый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#789899',
    DMC: '926',
    nameColorEnd: 'Grey Green — med',
    nameColorRu: 'Серо-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c5d2cf',
    DMC: '927',
    nameColorEnd: 'Grey Green — lt',
    nameColorRu: 'Серо-зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e5eae9',
    DMC: '928',
    nameColorEnd: 'Grey Green — vy lt',
    nameColorRu: 'Серо-зеленый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#435e67',
    DMC: '930',
    nameColorEnd: 'Antique Blue — dk',
    nameColorRu: 'Античный синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#678997',
    DMC: '931',
    nameColorEnd: 'Antique Blue — med',
    nameColorRu: 'Античный синий, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8faeb9',
    DMC: '932',
    nameColorEnd: 'Antique Blue — lt',
    nameColorRu: 'Античный синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4d4c34',
    DMC: '934',
    nameColorEnd: 'Black Avocado Green — dk',
    nameColorRu: 'Черно-зеленого авокадо, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4b5035',
    DMC: '935',
    nameColorEnd: 'Black Avocado Green — med',
    nameColorRu: 'Черно-зеленого авокадо, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#5d5c2b',
    DMC: '936',
    nameColorEnd: 'Avocado Green — vy dk',
    nameColorRu: 'Авокадо, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4f5925',
    DMC: '937',
    nameColorEnd: 'Avocado Green — med',
    nameColorRu: 'Авокадо, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#3b2811',
    DMC: '938',
    nameColorEnd: 'Coffee Brown — ultra dk',
    nameColorRu: 'Кофейный, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#02101c',
    DMC: '939',
    nameColorEnd: 'Navy Blue — vy dk',
    nameColorRu: 'Темно-синий, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#009a7b',
    DMC: '943',
    nameColorEnd: 'Aquamarine — med',
    nameColorRu: 'Аквамарин, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e3be8e',
    DMC: '945',
    nameColorEnd: 'Tawny',
    nameColorRu: 'Рыжевато-коричневый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e15729',
    DMC: '946',
    nameColorEnd: 'Burnt Orange — med',
    nameColorRu: 'Оранжево-жженный, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f26922',
    DMC: '947',
    nameColorEnd: 'Burnt Orange',
    nameColorRu: 'Оранжево-жженный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#feebe2',
    DMC: '948',
    nameColorEnd: 'Peach — vy lt',
    nameColorRu: 'Персиковый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e7ceb9',
    DMC: '950',
    nameColorEnd: 'Desert Sand — lt',
    nameColorRu: 'Пустынного песка, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f2e0ce',
    DMC: '951',
    nameColorEnd: 'Tawny — lt',
    nameColorRu: 'Рыжевато-коричневый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#abd58b',
    DMC: '954',
    nameColorEnd: 'Nile Green',
    nameColorRu: 'Мутно-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b4e8b3',
    DMC: '955',
    nameColorEnd: 'Nile Green — lt',
    nameColorRu: 'Мутно-зеленый, св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#ff7a90', DMC: '956', nameColorEnd: 'Geranium', nameColorRu: 'Герань', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#f9afb7',
    DMC: '957',
    nameColorEnd: 'Geranium — pale',
    nameColorRu: 'Герань, бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#51c0bb',
    DMC: '958',
    nameColorEnd: 'Seagreen — dk',
    nameColorRu: 'Морской воды, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8fd3d4',
    DMC: '959',
    nameColorEnd: 'Seagreen — med',
    nameColorRu: 'Морской воды, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#df6877',
    DMC: '961',
    nameColorEnd: 'Dusty Rose — dk',
    nameColorRu: 'Пыльной розы, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f08d9f',
    DMC: '962',
    nameColorEnd: 'Dusty Rose — med',
    nameColorRu: 'Пыльной розы, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fad0d5',
    DMC: '963',
    nameColorEnd: 'Dusty Rose — ultra vy lt',
    nameColorRu: 'Пыльной розы, очень св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9cd3cc',
    DMC: '964',
    nameColorEnd: 'Seagreen — lt',
    nameColorRu: 'Морской воды, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bbd7ae',
    DMC: '966',
    nameColorEnd: 'Baby Green — med',
    nameColorRu: 'Нежно зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fbdbcd',
    DMC: '967',
    nameColorEnd: 'Apricot — vy lt',
    nameColorRu: 'Абрикосовый оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ff781e',
    DMC: '970',
    nameColorEnd: 'Pumpkin — bright',
    nameColorRu: 'Тыквенный, яркий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fc7e0c',
    DMC: '971',
    nameColorEnd: 'Pumpkin',
    nameColorRu: 'Тыквенный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ffb401',
    DMC: '972',
    nameColorEnd: 'Canary — deep',
    nameColorRu: 'Канареечный, глубокий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ffe21a',
    DMC: '973',
    nameColorEnd: 'Canary — bright',
    nameColorRu: 'Канареечный, яркий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#945c2d',
    DMC: '975',
    nameColorEnd: 'Golden Brown — dk',
    nameColorRu: 'Золотисто-коричневый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e6973f',
    DMC: '976',
    nameColorEnd: 'Golden Brown — med',
    nameColorRu: 'Золотисто-коричневый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e59034',
    DMC: '977',
    nameColorEnd: 'Golden Brown — lt',
    nameColorRu: 'Золотисто-коричневый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#1f561f',
    DMC: '986',
    nameColorEnd: 'Forest Green — vy dk',
    nameColorRu: 'Зеленый лесной, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#568357',
    DMC: '987',
    nameColorEnd: 'Forest Green — dk',
    nameColorRu: 'Зеленый лесной, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#76996c',
    DMC: '988',
    nameColorEnd: 'Forest Green — med',
    nameColorRu: 'Зеленый лесной, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#87a462',
    DMC: '989',
    nameColorEnd: 'Forest Green',
    nameColorRu: 'Зеленый лесной',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#176a59',
    DMC: '991',
    nameColorEnd: 'Aquamarine — dk',
    nameColorRu: 'Аквамарин, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6cbfa8',
    DMC: '992',
    nameColorEnd: 'Aquamarine — lt',
    nameColorRu: 'Аквамарин, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8ec2b3',
    DMC: '993',
    nameColorEnd: 'Aquamarine — vy lt',
    nameColorRu: 'Аквамарин, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#0064b0',
    DMC: '995',
    nameColorEnd: 'Electric Blue — dk',
    nameColorRu: 'Электрик синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#57baf5',
    DMC: '996',
    nameColorEnd: 'Electric Blue — med',
    nameColorRu: 'Электрик синий, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#635f2f',
    DMC: '3011',
    nameColorEnd: 'Khaki Green — dk',
    nameColorRu: 'Хаки, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9b9648',
    DMC: '3012',
    nameColorEnd: 'Khaki Green — med',
    nameColorRu: 'Хаки, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#999c6c',
    DMC: '3013',
    nameColorEnd: 'Khaki Green — lt',
    nameColorRu: 'Хаки, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#3b2e08',
    DMC: '3021',
    nameColorEnd: 'Brown Grey — vy dk',
    nameColorRu: 'Коричнево-серый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#938e6e',
    DMC: '3022',
    nameColorEnd: 'Brown Grey — med',
    nameColorRu: 'Коричнево-серый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b2ae95',
    DMC: '3023',
    nameColorEnd: 'Brown Grey — lt',
    nameColorRu: 'Коричнево-серый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#dcdcd7',
    DMC: '3024',
    nameColorEnd: 'Brown Grey — vy lt',
    nameColorRu: 'Коричнево-серый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#442e10',
    DMC: '3031',
    nameColorEnd: 'Mocha Brown — vy dk',
    nameColorRu: 'Мокка, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ada183',
    DMC: '3032',
    nameColorEnd: 'Mocha Brown — med',
    nameColorRu: 'Мокка, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d7d0c2',
    DMC: '3033',
    nameColorEnd: 'Mocha Brown — vy lt',
    nameColorRu: 'Мокка, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#966e6e',
    DMC: '3041',
    nameColorEnd: 'Antique Violet — med',
    nameColorRu: 'Антично фиолетовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ccc1d0',
    DMC: '3042',
    nameColorEnd: 'Antique Violet — lt',
    nameColorRu: 'Антично фиолетовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b19563',
    DMC: '3045',
    nameColorEnd: 'Yellow Beige — dk',
    nameColorRu: 'Желтовато-бежевый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ccbc7d',
    DMC: '3046',
    nameColorEnd: 'Yellow Beige — med',
    nameColorRu: 'Желтовато-бежевый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ececd2',
    DMC: '3047',
    nameColorEnd: 'Yellow Beige — lt',
    nameColorRu: 'Желтовато-бежевый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6d6f42',
    DMC: '3051',
    nameColorEnd: 'Green Grey — dk',
    nameColorRu: 'Серо-зеленый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#899770',
    DMC: '3052',
    nameColorEnd: 'Green Grey — med',
    nameColorRu: 'Серо-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bac28b',
    DMC: '3053',
    nameColorEnd: 'Green Grey',
    nameColorRu: 'Серо-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#cda072',
    DMC: '3064',
    nameColorEnd: 'Desert Sand',
    nameColorRu: 'Пустынного песка',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e3e6dc',
    DMC: '3072',
    nameColorEnd: 'Beaver Grey — vy lt',
    nameColorRu: 'Боброво-серый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fff3ad',
    DMC: '3078',
    nameColorEnd: 'Golden Yellow — vy lt',
    nameColorRu: 'Желтый золотой, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c6d3e1',
    DMC: '3325',
    nameColorEnd: 'Baby Blue — lt',
    nameColorRu: 'Нежно голубой, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f7b4b7',
    DMC: '3326',
    nameColorEnd: 'Rose — lt',
    nameColorRu: 'Розы, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c36154',
    DMC: '3328',
    nameColorEnd: 'Salmon — dk',
    nameColorRu: 'Лососевый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f38351',
    DMC: '3340',
    nameColorEnd: 'Apricot — med',
    nameColorRu: 'Абрикосовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fbbe9d',
    DMC: '3341',
    nameColorEnd: 'Apricot',
    nameColorRu: 'Абрикосовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#486131',
    DMC: '3345',
    nameColorEnd: 'Hunter Green — dk',
    nameColorRu: 'Защитный, грязновато зеленый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6a823d',
    DMC: '3346',
    nameColorEnd: 'Hunter Green',
    nameColorRu: 'Защитный, грязновато зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#78983b',
    DMC: '3347',
    nameColorEnd: 'Yellow Green — med',
    nameColorRu: 'Желто-зеленый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e3ee9f',
    DMC: '3348',
    nameColorEnd: 'Yellow Green — lt',
    nameColorRu: 'Желто-зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b95569',
    DMC: '3350',
    nameColorEnd: 'Dusty Rose — ultra dk',
    nameColorRu: 'Пыльной розы, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e3a5aa',
    DMC: '3354',
    nameColorEnd: 'Dusty Rose — lt',
    nameColorRu: 'Пыльной розы, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#2e3d1a',
    DMC: '3362',
    nameColorEnd: 'Pine Green — dk',
    nameColorRu: 'Сосновый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#72885f',
    DMC: '3363',
    nameColorEnd: 'Pine Green — med',
    nameColorRu: 'Сосновый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#85905c',
    DMC: '3364',
    nameColorEnd: 'Pine Green',
    nameColorRu: 'Сосновый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#2d1705',
    DMC: '3371',
    nameColorEnd: 'Black Brown',
    nameColorRu: 'Черно-коричневый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b34e8c',
    DMC: '3607',
    nameColorEnd: 'Plum — lt',
    nameColorRu: 'Сливовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c07ba3',
    DMC: '3608',
    nameColorEnd: 'Plum — vy lt',
    nameColorRu: 'Сливовый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e9afd3',
    DMC: '3609',
    nameColorEnd: 'Plum — ultra lt',
    nameColorRu: 'Сливовый, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#7d3248',
    DMC: '3685',
    nameColorEnd: 'Mauve — vy dk',
    nameColorRu: 'Розовато-лиловый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c2596d',
    DMC: '3687',
    nameColorEnd: 'Mauve',
    nameColorRu: 'Розовато-лиловый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e6849a',
    DMC: '3688',
    nameColorEnd: 'Mauve — med',
    nameColorRu: 'Розовато-лиловый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e8b9c5',
    DMC: '3689',
    nameColorEnd: 'Mauve — lt',
    nameColorRu: 'Розовато-лиловый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f65d5b',
    DMC: '3705',
    nameColorEnd: 'Melon — dk',
    nameColorRu: 'Дыни, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ff988e',
    DMC: '3706',
    nameColorEnd: 'Melon — med',
    nameColorRu: 'Дыни, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fcbbc1',
    DMC: '3708',
    nameColorEnd: 'Melon — lt',
    nameColorRu: 'Дыни, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#db7d73',
    DMC: '3712',
    nameColorEnd: 'Salmon — med',
    nameColorRu: 'Лососевый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fcdcda',
    DMC: '3713',
    nameColorEnd: 'Salmon — vy lt',
    nameColorRu: 'Лососевый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fcb1ba',
    DMC: '3716',
    nameColorEnd: 'Dusty Rose — vy lt',
    nameColorRu: 'Пыльной розы, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#aa5048',
    DMC: '3721',
    nameColorEnd: 'Shell Pink — dk',
    nameColorRu: 'Розовых ракушек, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a45d55',
    DMC: '3722',
    nameColorEnd: 'Shell Pink — med',
    nameColorRu: 'Розовых ракушек, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#874c49',
    DMC: '3726',
    nameColorEnd: 'Antique Mauve — dk',
    nameColorRu: 'Античный розовато-лиловый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e6bcc3',
    DMC: '3727',
    nameColorEnd: 'Antique Mauve — lt',
    nameColorRu: 'Античный розовато-лиловый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c65a6b',
    DMC: '3731',
    nameColorEnd: 'Dusty Rose — vy dk',
    nameColorRu: 'Пыльной розы, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#eda6ac',
    DMC: '3733',
    nameColorEnd: 'Dusty Rose',
    nameColorRu: 'Пыльной розы',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#72535a',
    DMC: '3740',
    nameColorEnd: 'Antique Violet — dk',
    nameColorRu: 'Антично фиолетовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c7bac7',
    DMC: '3743',
    nameColorEnd: 'Antique Violet — vy lt',
    nameColorRu: 'Антично фиолетовый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8572a4',
    DMC: '3746',
    nameColorEnd: 'Blue Violet — dk',
    nameColorRu: 'Сине-фиолетовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bcc0d8',
    DMC: '3747',
    nameColorEnd: 'Blue Violet — vy lt',
    nameColorRu: 'Сине-фиолетовый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#444d58',
    DMC: '3750',
    nameColorEnd: 'Antique Blue — vy dk',
    nameColorRu: 'Античный синий, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#bbc8d6',
    DMC: '3752',
    nameColorEnd: 'Antique Blue — vy lt',
    nameColorRu: 'Античный синий, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ccd5da',
    DMC: '3753',
    nameColorEnd: 'Antique Blue — ultra vy lt',
    nameColorRu: 'Античный синий, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9fbbd5',
    DMC: '3755',
    nameColorEnd: 'Baby Blue',
    nameColorRu: 'Нежно голубой',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e8edf3',
    DMC: '3756',
    nameColorEnd: 'Baby Blue — ultra vy lt',
    nameColorRu: 'Нежно голубой, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4f819d',
    DMC: '3760',
    nameColorEnd: 'Wedgwood — med',
    nameColorRu: 'Пыльно-синий, ср. (гжель)',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b8dae9',
    DMC: '3761',
    nameColorEnd: 'Sky Blue — lt',
    nameColorRu: 'Небесно голубой, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#296e87',
    DMC: '3765',
    nameColorEnd: 'Peacock Blue — vy dk',
    nameColorRu: 'Переливчатый синий, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#7cbec6',
    DMC: '3766',
    nameColorEnd: 'Peacock Blue — lt',
    nameColorRu: 'Переливчатый синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6b8084',
    DMC: '3768',
    nameColorEnd: 'Grey Green — dk',
    nameColorRu: 'Серо-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f8eedc',
    DMC: '3770',
    nameColorEnd: 'Tawny — vy lt',
    nameColorRu: 'Рыжевато-коричневый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e8b58f',
    DMC: '3771',
    nameColorEnd: 'Terra Cotta — ultra vy lt',
    nameColorRu: 'Терракотовый, ультра оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b8846c',
    DMC: '3772',
    nameColorEnd: 'Desert Sand — vy dk',
    nameColorRu: 'Пустынного песка, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d8b39d',
    DMC: '3773',
    nameColorEnd: 'Desert Sand — med',
    nameColorRu: 'Пустынного песка, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f6e1d0',
    DMC: '3774',
    nameColorEnd: 'Desert Sand — vy lt',
    nameColorRu: 'Пустынного песка, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c27d45',
    DMC: '3776',
    nameColorEnd: 'Mahogany — lt',
    nameColorRu: 'Красного дерева, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#892b21',
    DMC: '3777',
    nameColorEnd: 'Terra Cotta — vy dk',
    nameColorRu: 'Терракотовый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c4856f',
    DMC: '3778',
    nameColorEnd: 'Terra Cotta — lt',
    nameColorRu: 'Терракотовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f2c6b8',
    DMC: '3779',
    nameColorEnd: 'Terra Cotta — ultra vy lt',
    nameColorRu: 'Терракотовый, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#5c4c2d',
    DMC: '3781',
    nameColorEnd: 'Mocha Brown — dk',
    nameColorRu: 'Мокка, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d2caba',
    DMC: '3782',
    nameColorEnd: 'Mocha Brown — lt',
    nameColorRu: 'Мокка, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#605b45',
    DMC: '3787',
    nameColorEnd: 'Brown Grey — dk',
    nameColorRu: 'Коричнево-серый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#978266',
    DMC: '3790',
    nameColorEnd: 'Beige Grey — ultra dk',
    nameColorRu: 'Бежево-серый, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#2f3b36',
    DMC: '3799',
    nameColorEnd: 'Pewter Grey — vy dk',
    nameColorRu: 'Оловянно серый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e65952',
    DMC: '3801',
    nameColorEnd: 'Christmas Red — lt',
    nameColorRu: 'Рождественский красный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6f2e35',
    DMC: '3802',
    nameColorEnd: 'Antique Mauve — vy dk',
    nameColorRu: 'Античный розовато-лиловый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#863248',
    DMC: '3803',
    nameColorEnd: 'Mauve — dk',
    nameColorRu: 'Розовато-лиловый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c33c62',
    DMC: '3804',
    nameColorEnd: 'Cyclamen Pink — dk',
    nameColorRu: 'Розового цикламена, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ce507f',
    DMC: '3805',
    nameColorEnd: 'Cyclamen Pink',
    nameColorRu: 'Розового цикламена',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f19ac2',
    DMC: '3806',
    nameColorEnd: 'Cyclamen Pink — lt',
    nameColorRu: 'Розового цикламена, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#073563',
    DMC: '3807',
    nameColorEnd: 'Cornflower Blue',
    nameColorRu: 'Васильковый, кобальтовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#0c464b',
    DMC: '3808',
    nameColorEnd: 'Turquoise — ultra vy dk',
    nameColorRu: 'Бирюзовый, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#1c869b',
    DMC: '3809',
    nameColorEnd: 'Turquoise — vy dk',
    nameColorRu: 'Бирюзовый, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#4fa1a9',
    DMC: '3810',
    nameColorEnd: 'Turquoise — dk',
    nameColorRu: 'Бирюзовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c4e7e8',
    DMC: '3811',
    nameColorEnd: 'Turquoise — vy lt',
    nameColorRu: 'Бирюзовый, оч.св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#008679',
    DMC: '3812',
    nameColorEnd: 'Seagreen — vy dk',
    nameColorRu: 'Морской воды, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b8cebe',
    DMC: '3813',
    nameColorEnd: 'Blue Green — lt',
    nameColorRu: 'Сине-зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#3f8878',
    DMC: '3814',
    nameColorEnd: 'Aquamarine',
    nameColorRu: 'Аквамарин',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#538a6d',
    DMC: '3815',
    nameColorEnd: 'Celadon Green — dk',
    nameColorRu: 'Серовато-зеленый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#699d85',
    DMC: '3816',
    nameColorEnd: 'Celadon Green',
    nameColorRu: 'Серовато-зеленый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a6c5b4',
    DMC: '3817',
    nameColorEnd: 'Celadon Green — lt',
    nameColorRu: 'Серовато-зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#005d2e',
    DMC: '3818',
    nameColorEnd: 'Emerald Green — ultra vy dk',
    nameColorRu: 'Изумрудный, ультра т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d2d057',
    DMC: '3819',
    nameColorEnd: 'Moss Green — lt',
    nameColorRu: 'Мох, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ddb442',
    DMC: '3820',
    nameColorEnd: 'Straw — dk',
    nameColorRu: 'Соломенный, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e2b73a',
    DMC: '3821',
    nameColorEnd: 'Straw',
    nameColorRu: 'Соломенный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f1d863',
    DMC: '3822',
    nameColorEnd: 'Straw — lt',
    nameColorRu: 'Соломенный, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fffcdc',
    DMC: '3823',
    nameColorEnd: 'Yellow — ultra pale',
    nameColorRu: 'Желтый, ультра бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fbccb8',
    DMC: '3824',
    nameColorEnd: 'Apricot — lt',
    nameColorRu: 'Абрикосовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fdc391',
    DMC: '3825',
    nameColorEnd: 'Pumpkin — pale',
    nameColorRu: 'Тыквенный, бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c38c55',
    DMC: '3826',
    nameColorEnd: 'Golden Brown',
    nameColorRu: 'Золотовато-коричневый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e8aa5f',
    DMC: '3827',
    nameColorEnd: 'Golden Brown — pale',
    nameColorRu: 'Золотовато-коричневый, бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#af8846',
    DMC: '3828',
    nameColorEnd: 'Hazelnut Brown',
    nameColorRu: 'Фундука',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a47829',
    DMC: '3829',
    nameColorEnd: 'Old Gold — vy dk',
    nameColorRu: 'Старого золота, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b97161',
    DMC: '3830',
    nameColorEnd: 'Terra Cotta',
    nameColorRu: 'Терракотовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b33034',
    DMC: '3831',
    nameColorEnd: 'Raspberry — dk',
    nameColorRu: 'Малиновый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b33034',
    DMC: '3832',
    nameColorEnd: 'Raspberry — med',
    nameColorRu: 'Малиновый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e8868c',
    DMC: '3833',
    nameColorEnd: 'Raspberry — lt',
    nameColorRu: 'Малиновый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#642441',
    DMC: '3834',
    nameColorEnd: 'Grape — dk',
    nameColorRu: 'Красного винограда, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#784775',
    DMC: '3835',
    nameColorEnd: 'Grape — med',
    nameColorRu: 'Красного винограда, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c1aec2',
    DMC: '3836',
    nameColorEnd: 'Grape — lt',
    nameColorRu: 'Красного винограда, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#7c4087',
    DMC: '3837',
    nameColorEnd: 'Lavender — ultra dk',
    nameColorRu: 'Лаванда, ультра тёмный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#62669a',
    DMC: '3838',
    nameColorEnd: 'Lavender Blue — dk',
    nameColorRu: 'Лавандово-синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#94a8c9',
    DMC: '3839',
    nameColorEnd: 'Lavender Blue — med',
    nameColorRu: 'Лавандово-синий, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c1d4ec',
    DMC: '3840',
    nameColorEnd: 'Lavender Blue — lt',
    nameColorRu: 'Лавандово-синий, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#cbdde7',
    DMC: '3841',
    nameColorEnd: 'Baby Blue — pale',
    nameColorRu: 'Нежно голубой, бледный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#12557e',
    DMC: '3842',
    nameColorEnd: 'Wedgwood — dk',
    nameColorRu: 'Пыльно-синий, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#0095d3',
    DMC: '3843',
    nameColorEnd: 'Electric Blue',
    nameColorRu: 'Волнующе синий',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#0095d3',
    DMC: '3844',
    nameColorEnd: 'Bright Turquoise — dk',
    nameColorRu: 'Ярко-бирюзовый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#01cbec',
    DMC: '3845',
    nameColorEnd: 'Bright Turquoise — med',
    nameColorRu: 'Ярко-бирюзовый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#63d3e1',
    DMC: '3846',
    nameColorEnd: 'Bright Turquoise — lt',
    nameColorRu: 'Ярко-бирюзовый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#00604e',
    DMC: '3847',
    nameColorEnd: 'Teal Green — dk',
    nameColorRu: 'Цвет рабочего стола Windows, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#42917f',
    DMC: '3848',
    nameColorEnd: 'Teal Green — med',
    nameColorRu: 'Цвет рабочего стола Windows, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#6eb2a7',
    DMC: '3849',
    nameColorEnd: 'Teal Green — lt',
    nameColorRu: 'Цвет рабочего стола Windows, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#08926f',
    DMC: '3850',
    nameColorEnd: 'Bright Green — dk',
    nameColorRu: 'Ярко-зеленый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#56b69c',
    DMC: '3851',
    nameColorEnd: 'Bright Green — lt',
    nameColorRu: 'Ярко-зеленый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#cc972b',
    DMC: '3852',
    nameColorEnd: 'Straw — vy dk',
    nameColorRu: 'Соломенный, оч.т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#fc9749',
    DMC: '3853',
    nameColorEnd: 'Autumn Gold — dk',
    nameColorRu: 'Золотой осенний, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f7b25c',
    DMC: '3854',
    nameColorEnd: 'Autumn Gold — med',
    nameColorRu: 'Золотой осенний, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f7ca84',
    DMC: '3855',
    nameColorEnd: 'Autumn Gold — lt',
    nameColorRu: 'Золотой осенний, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ebbc9a',
    DMC: '3856',
    nameColorEnd: 'Mahogany — ultra vy lt',
    nameColorRu: 'Красного дерева, ультра св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#804133',
    DMC: '3857',
    nameColorEnd: 'Rosewood — dk',
    nameColorRu: 'Розового дерева, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#8d5745',
    DMC: '3858',
    nameColorEnd: 'Rosewood — med',
    nameColorRu: 'Розового дерева, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#b68472',
    DMC: '3859',
    nameColorEnd: 'Rosewood — lt',
    nameColorRu: 'Розового дерева, св.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#947974', DMC: '3860', nameColorEnd: 'Cocoa', nameColorRu: 'Какао', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#9e887f',
    DMC: '3861',
    nameColorEnd: 'Cocoa — lt',
    nameColorRu: 'Какао, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#845f2e',
    DMC: '3862',
    nameColorEnd: 'Mocha Beige — dk',
    nameColorRu: 'Темно-коричневый бежевый, т.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#a4866c',
    DMC: '3863',
    nameColorEnd: 'Mocha Beige — med',
    nameColorRu: 'Темно-коричневый бежевый, ср.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#c9af93',
    DMC: '3864',
    nameColorEnd: 'Mocha Beige — lt',
    nameColorRu: 'Темно-коричневый бежевый, св.',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#faf9f5',
    DMC: '3865',
    nameColorEnd: 'Winter White',
    nameColorRu: 'Снежно белый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#e7e5dd',
    DMC: '3866',
    nameColorEnd: 'Mocha Brown — ultra vy lt',
    nameColorRu: 'Мокка, ультра св.',
    count: 0,
  },
];
