export interface IColor {
  id: string;
  color: string;
  name_color_eng: string;
  dmc: string;
  name_color_ru: string;
  count: string;
  error?: string;
}

export const objectColor: IColor[] = [
  {
    id: crypto.randomUUID(),
    color: '#FFFFFF',
    dmc: 'blanc',
    name_color_eng: 'White',
    name_color_ru: 'Белый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#E9E9D4',
    dmc: 'Ecru',
    name_color_eng: 'Ecru',
    name_color_ru: 'Кремовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    dmc: 'B5200',
    color: '#FFFFFF',
    name_color_eng: 'Ultra white',
    name_color_ru: 'Белоснежный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9F3845',
    dmc: '150',
    name_color_eng: 'Dusty Rose — ultra vy dk',
    name_color_ru: 'Пыльная роза, ультра очень тёмный (оч.т.)',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#F2BCC5',
    dmc: '151',
    name_color_eng: 'Dusty Rose — vy lt',
    name_color_ru: 'Пыльная роза, очень светлый (оч.св.)',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#CFA296',
    dmc: '152',
    name_color_eng: 'Shell Pink — med lt',
    name_color_ru: 'Розовых ракушек, средне светлый (ср.св.)',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#DEBCD9',
    dmc: '153',
    name_color_eng: 'Violet — vy lt',
    name_color_ru: 'Фиолетовый, очень светлый (оч.св)',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4D2E3D',
    dmc: '154',
    name_color_eng: 'Grape — vy dk',
    name_color_ru: 'Красного винограда, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#908BC3',
    dmc: '155',
    name_color_eng: 'Blue Violet — med dk',
    name_color_ru: 'Сине-фиолетовый, ср.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8B9AC5',
    dmc: '156',
    name_color_eng: 'Blue Violet — med lt',
    name_color_ru: 'Сине-фиолетовый, ср.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ABC2DE',
    dmc: '157',
    name_color_eng: 'Cornflower Blue — vy lt',
    name_color_ru: 'Васильковый, кобальтовый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#465082',
    dmc: '158',
    name_color_eng: 'Cornflower Blue-med vy dk',
    name_color_ru: 'Васильковый, кобальтовый, ср.оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#A7B4CD',
    dmc: '159',
    name_color_eng: 'Gray Blue-lt',
    name_color_ru: 'Серо-синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8290AE',
    dmc: '160',
    name_color_eng: 'Gray Blue-med',
    name_color_ru: 'Серо-синий, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#667594',
    dmc: '161',
    name_color_eng: 'Gray Blue',
    name_color_ru: 'Серо-синий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#BDDBE6',
    dmc: '162',
    name_color_eng: 'Blue-ultra vy lt',
    name_color_ru: 'Голубой, ультра оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#569571',
    dmc: '163',
    name_color_eng: 'Celadon Green-med',
    name_color_ru: 'Серовато-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9FCC8D',
    dmc: '164',
    name_color_eng: 'Forest Green-lt',
    name_color_ru: 'Зеленый лесной, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#DAD878',
    dmc: '165',
    name_color_eng: 'Moss Green-vylt',
    name_color_ru: 'Мох, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#BFBB20',
    dmc: '166',
    name_color_eng: 'Moss Green-med lt',
    name_color_ru: 'Мох, ср.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9F8447',
    dmc: '167',
    name_color_eng: 'Yellow Beige-vy dk',
    name_color_ru: 'Желтовато-бежевый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#B4C3C1',
    dmc: '168',
    name_color_eng: 'Pewter-vy lt',
    name_color_ru: 'Оловянный, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8B9A94',
    dmc: '169',
    name_color_eng: 'Pewter-lt',
    name_color_ru: 'Оловянный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9870AC',
    dmc: '208',
    name_color_eng: 'Lavender-vy dk',
    name_color_ru: 'Лаванда, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#B693B6',
    dmc: '209',
    name_color_eng: 'Lavender-dk',
    name_color_ru: 'Лаванда, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#C9AFDD',
    dmc: '210',
    name_color_eng: 'Lavender-med',
    name_color_ru: 'Лаванда, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#D4C3E4',
    dmc: '211',
    name_color_eng: 'Lavender-lt',
    name_color_ru: 'Лаванда, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#884238',
    dmc: '221',
    name_color_eng: 'Shel lPink-vy dk',
    name_color_ru: 'Розовых ракушек, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#BB817B',
    dmc: '223',
    name_color_eng: 'Shell Pink-lt',
    name_color_ru: 'Розовых ракушек, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#DFB3A6',
    dmc: '224',
    name_color_eng: 'ShellPink-vy lt',
    name_color_ru: 'Розовых ракушек, оч. св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#784E24',
    dmc: '225',
    name_color_eng: 'ShellPink-ultra vy lt',
    name_color_ru: 'Розовых ракушек, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#784E24',
    dmc: '300',
    name_color_eng: 'Mahogany-vy dk',
    name_color_ru: 'Красного дерева, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#AA6730',
    dmc: '301',
    name_color_eng: 'Mahogany-med',
    name_color_ru: 'Красного дерева, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9E3332',
    dmc: '304',
    name_color_eng: 'Christmas Red-med',
    name_color_ru: 'Рождественский красный, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#F6E311',
    dmc: '307',
    name_color_eng: 'Lemon',
    name_color_ru: 'Лимонный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#B84351',
    dmc: '309',
    name_color_eng: 'Rose-dk',
    name_color_ru: 'Розы, т.',
    count: 0,
  },
  { id: crypto.randomUUID(), color: '#000000', dmc: '310', name_color_eng: 'Black', name_color_ru: 'Черный', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#30506F',
    dmc: '311',
    name_color_eng: 'Navy Blue-med',
    name_color_ru: 'Темно-синий, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#386189',
    dmc: '312',
    name_color_eng: 'Navy Blue-lt',
    name_color_ru: 'Темно-синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8E5D5C',
    dmc: '315',
    name_color_eng: 'Antique Mauve-med dk',
    name_color_ru: 'Античный розовато-лиловый, ср.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#BF889C',
    dmc: '316',
    name_color_eng: 'Antique Mauve-med',
    name_color_ru: 'Античный розовато-лиловый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#697275',
    dmc: '317',
    name_color_eng: 'Pewter Grey',
    name_color_ru: 'Оловянносерый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#A0A7B0',
    dmc: '318',
    name_color_eng: 'Steel Grey-lt',
    name_color_ru: 'Стальной, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#35633D',
    dmc: '319',
    name_color_eng: 'Pistachio Green-vy dk',
    name_color_ru: 'Фисташково-зеленый,оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#71a072',
    dmc: '320',
    name_color_eng: 'Pistachio Green-med',
    name_color_ru: 'Фисташково-зеленый,ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ce1f32',
    dmc: '321',
    name_color_eng: 'Christmas Red',
    name_color_ru: 'Рождественскийкрасный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#647e9d',
    dmc: '322',
    name_color_eng: 'NavyBlue-vy lt',
    name_color_ru: 'Темно-синий,оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a92332',
    dmc: '326',
    name_color_eng: 'Rose-vy dk',
    name_color_ru: 'Розы,оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#723657',
    dmc: '327',
    name_color_eng: 'Violet-vy dk',
    name_color_ru: 'Фиолетовый,оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6c5086',
    dmc: '333',
    name_color_eng: 'BlueViolet-vy dk',
    name_color_ru: 'Сине-фиолетовый,оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4c698c',
    dmc: '334',
    name_color_eng: 'BabyBlue-med',
    name_color_ru: 'Нежноголубой,ср.',
    count: '0',
  },
  { id: crypto.randomUUID(), color: '#e56d7f', dmc: '335', name_color_eng: 'Rose', name_color_ru: 'Розы', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#0c1225',
    dmc: '336',
    name_color_eng: 'Navy Blue',
    name_color_ru: 'Темно-синий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9389c1',
    dmc: '340',
    name_color_eng: 'Blue Violet-med',
    name_color_ru: 'Сине-фиолетовый,ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a2accd',
    dmc: '341',
    name_color_eng: 'Blue Violet-lt',
    name_color_ru: 'Сине-фиолетовый,св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bf3e31',
    dmc: '347',
    name_color_eng: 'Salmon — vy dk',
    name_color_ru: 'Лососевый,оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c24731',
    dmc: '349',
    name_color_eng: 'Coral-dk',
    name_color_ru: 'Коралловокрасный,т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e46647',
    dmc: '350',
    name_color_eng: 'Coral-med',
    name_color_ru: 'Кораллово красный,ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f78465',
    dmc: '351',
    name_color_eng: 'Coral',
    name_color_ru: 'Кораллово красный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f69d80',
    dmc: '352',
    name_color_eng: 'Coral-lt',
    name_color_ru: 'Коралловокрасный,св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fdbca1',
    dmc: '353',
    name_color_eng: 'Peach',
    name_color_ru: 'Персиковый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9a3b2d',
    dmc: '355',
    name_color_eng: 'TerraCotta-dk',
    name_color_ru: 'Терракотовый,т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a06757',
    dmc: '356',
    name_color_eng: 'TerraCotta-med',
    name_color_ru: 'Терракотовый,ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4c7047',
    dmc: '367',
    name_color_eng: 'PistachioGreen-dk',
    name_color_ru: 'Фисташково-зеленый,т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#91ab84',
    dmc: '368',
    name_color_eng: 'PistachioGreen-lt',
    name_color_ru: 'Фисташково-зеленый,св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ccdcbe',
    dmc: '369',
    name_color_eng: 'PistachioGreen-vy lt',
    name_color_ru: 'Фисташково-зеленый,оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bbaa55',
    dmc: '370',
    name_color_eng: 'Mustard-med',
    name_color_ru: 'Горчичный,ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a08f4d',
    dmc: '371',
    name_color_eng: 'Mustard',
    name_color_ru: 'Горчичный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9c8c4a',
    dmc: '372',
    name_color_eng: 'Mustard — lt',
    name_color_ru: 'Горчичный,св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#934d29',
    dmc: '400',
    name_color_eng: 'Mahogany — dk',
    name_color_ru: 'Красного дерева, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e8a76d',
    dmc: '402',
    name_color_eng: 'Mahogany — vy lt',
    name_color_ru: 'Красного дерева, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c49a87',
    dmc: '407',
    name_color_eng: 'Desert Sand — dk',
    name_color_ru: 'Пустынного песка, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#535657',
    dmc: '413',
    name_color_eng: 'Pewter Grey — dk',
    name_color_ru: 'Оловянно серый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#95909d',
    dmc: '414',
    name_color_eng: 'Steel Grey — dk',
    name_color_ru: 'Стальной, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d3d4db',
    dmc: '415',
    name_color_eng: 'Pearl Grey',
    name_color_ru: 'Жемчужно серый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#866226',
    dmc: '420',
    name_color_eng: 'Hazelnut Brown — dk',
    name_color_ru: 'Фундука, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d0ba79',
    dmc: '422',
    name_color_eng: 'Hazelnut Brown — lt',
    name_color_ru: 'Фундука, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#775437',
    dmc: '433',
    name_color_eng: 'Brown — med',
    name_color_ru: 'Коричневый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b78237',
    dmc: '434',
    name_color_eng: 'Brown — lt',
    name_color_ru: 'Коричневый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c4863a',
    dmc: '435',
    name_color_eng: 'Brown — vy lt',
    name_color_ru: 'Коричневый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c09557',
    dmc: '436',
    name_color_eng: 'Tan',
    name_color_ru: 'Желто-коричневый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d9b879',
    dmc: '437',
    name_color_eng: 'Tan — lt',
    name_color_ru: 'Желто-коричневый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f5d500',
    dmc: '444',
    name_color_eng: 'Lemon — dk',
    name_color_ru: 'Лимонный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f0ed85',
    dmc: '445',
    name_color_eng: 'Lemon — lt',
    name_color_ru: 'Лимонный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#978b81',
    dmc: '451',
    name_color_eng: 'Shell Grey — dk',
    name_color_ru: 'Серых ракушек, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bbaea6',
    dmc: '452',
    name_color_eng: 'Shell Grey — med',
    name_color_ru: 'Серых ракушек, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e3dcdb',
    dmc: '453',
    name_color_eng: 'Shell Grey — lt',
    name_color_ru: 'Серых ракушек, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#798738',
    dmc: '469',
    name_color_eng: 'Avocado Green',
    name_color_ru: 'Авокадо',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#98a859',
    dmc: '470',
    name_color_eng: 'Avocado Green — lt',
    name_color_ru: 'Авокадо, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#929937',
    dmc: '471',
    name_color_eng: 'Avocado Green — vy lt',
    name_color_ru: 'Авокадо, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#dee077',
    dmc: '472',
    name_color_eng: 'Avocado Green — ultra lt',
    name_color_ru: 'Авокадо, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#98232c',
    dmc: '498',
    name_color_eng: 'Christmas Red — dk',
    name_color_ru: 'Рождественский красный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#14361e',
    dmc: '500',
    name_color_eng: 'Blue Green — vy dk',
    name_color_ru: 'Сине-зеленый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#496f5c',
    dmc: '501',
    name_color_eng: 'Blue Green — dk',
    name_color_ru: 'Сине-зеленый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#799a83',
    dmc: '502',
    name_color_eng: 'Blue Green',
    name_color_ru: 'Сине-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8ebea9',
    dmc: '503',
    name_color_eng: 'Blue Green — med',
    name_color_ru: 'Сине-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d1e2d7',
    dmc: '504',
    name_color_eng: 'Blue Green — vy lt',
    name_color_ru: 'Сине-зеленый, оч.св.',
    count: '0',
  },
  { id: crypto.randomUUID(), color: '#418253', dmc: '505', name_color_eng: 'Jade', name_color_ru: 'Нефрит', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#166d92',
    dmc: '517',
    name_color_eng: 'Wedgwood — dk',
    name_color_ru: 'Пыльно-синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6b9cb9',
    dmc: '518',
    name_color_eng: 'Wedgwood — lt',
    name_color_ru: 'Пыльно-синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a8c6d8',
    dmc: '519',
    name_color_eng: 'Sky Blue',
    name_color_ru: 'Небесно голубой',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4f6035',
    dmc: '520',
    name_color_eng: 'Fern Green — dk',
    name_color_ru: 'Папоротниковый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#93a181',
    dmc: '522',
    name_color_eng: 'Fern Green',
    name_color_ru: 'Папоротниковый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a5a888',
    dmc: '523',
    name_color_eng: 'Fern Green — lt',
    name_color_ru: 'Папоротниковый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bec0a8',
    dmc: '524',
    name_color_eng: 'Fern Green — vy lt',
    name_color_ru: 'Папоротниковый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#504f50',
    dmc: '535',
    name_color_eng: 'Ash Grey — vy lt',
    name_color_ru: 'Пепельный, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f0e3d4',
    dmc: '543',
    name_color_eng: 'Beige Brown — ultra vy lt',
    name_color_ru: 'Бежево-коричневый, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#541244',
    dmc: '550',
    name_color_eng: 'Violet — vy dk',
    name_color_ru: 'Фиолетовый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#7b3f6c',
    dmc: '552',
    name_color_eng: 'Violet — med',
    name_color_ru: 'Фиолетовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a772a4',
    dmc: '553',
    name_color_eng: 'Violet',
    name_color_ru: 'Фиолетовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ae99b1',
    dmc: '554',
    name_color_eng: 'Violet — lt',
    name_color_ru: 'Фиолетовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#377557',
    dmc: '561',
    name_color_eng: 'Jade — vy dk',
    name_color_ru: 'Нефрит, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#599b6d',
    dmc: '562',
    name_color_eng: 'Jade — med',
    name_color_ru: 'Нефрит, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#87c39e',
    dmc: '563',
    name_color_eng: 'Jade — lt',
    name_color_ru: 'Нефрит, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9cd0ab',
    dmc: '564',
    name_color_eng: 'Jade — vy lt',
    name_color_ru: 'Нефрит, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#68772d',
    dmc: '580',
    name_color_eng: 'Moss Green — dk',
    name_color_ru: 'Мох, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9fa146',
    dmc: '581',
    name_color_eng: 'Moss Green',
    name_color_ru: 'Мох',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#70aeb4',
    dmc: '597',
    name_color_eng: 'Turquoise',
    name_color_ru: 'Бирюзовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#97ccca',
    dmc: '598',
    name_color_eng: 'Turquoise — lt',
    name_color_ru: 'Бирюзовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bf1c48',
    dmc: '600',
    name_color_eng: 'Cranberry — vy dk',
    name_color_ru: 'Клюквенный, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d34067',
    dmc: '601',
    name_color_eng: 'Cranberry — dk',
    name_color_ru: 'Клюквенный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ca0b51',
    dmc: '602',
    name_color_eng: 'Cranberry — med',
    name_color_ru: 'Клюквенный, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ef7ba1',
    dmc: '603',
    name_color_eng: 'Cranberry',
    name_color_ru: 'Клюквенный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ec9ab9',
    dmc: '604',
    name_color_eng: 'Cranberry — lt',
    name_color_ru: 'Клюквенный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#faccdb',
    dmc: '605',
    name_color_eng: 'Cranberry — vy lt',
    name_color_ru: 'Клюквенный, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ea592c',
    dmc: '606',
    name_color_eng: 'Bright Orange Red',
    name_color_ru: 'Яркий красно-оранжевый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f06e46',
    dmc: '608',
    name_color_eng: 'Bright Orange',
    name_color_ru: 'Ярко оранжевый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#806638',
    dmc: '610',
    name_color_eng: 'Drab Brown — vy dk',
    name_color_ru: 'Тускло-коричневый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9e9072',
    dmc: '611',
    name_color_eng: 'Drab Brown — dk',
    name_color_ru: 'Тускло-коричневый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#917d4a',
    dmc: '612',
    name_color_eng: 'Drab Brown — med',
    name_color_ru: 'Тускло-коричневый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bcae83',
    dmc: '613',
    name_color_eng: 'Drab Brown — lt',
    name_color_ru: 'Тускло-коричневый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8c593e',
    dmc: '632',
    name_color_eng: 'Desert Sand — ultra vy dk',
    name_color_ru: 'Пустынного песка, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#938962',
    dmc: '640',
    name_color_eng: 'Beige Grey — vy dk',
    name_color_ru: 'Бежево-серый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bab599',
    dmc: '642',
    name_color_eng: 'Beige Grey — dk',
    name_color_ru: 'Бежево-серый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d6d3c1',
    dmc: '644',
    name_color_eng: 'Beige Grey — med',
    name_color_ru: 'Бежево-серый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#747e65',
    dmc: '645',
    name_color_eng: 'Beaver Grey — vy dk',
    name_color_ru: 'Боброво-серый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#97978e',
    dmc: '646',
    name_color_eng: 'Beaver Grey — dk',
    name_color_ru: 'Боброво-серый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#abafa3',
    dmc: '647',
    name_color_eng: 'Beaver Grey — med',
    name_color_ru: 'Боброво-серый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#babfad',
    dmc: '648',
    name_color_eng: 'Beaver Grey — lt',
    name_color_ru: 'Боброво-серый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d12627',
    dmc: '666',
    name_color_eng: 'Christmas Red — bright',
    name_color_ru: 'Рождественский красный, яркий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#eed7a1',
    dmc: '676',
    name_color_eng: 'Old Gold — lt',
    name_color_ru: 'Старого золота, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ede0ba',
    dmc: '677',
    name_color_eng: 'Old Gold — vy lt',
    name_color_ru: 'Старого золота, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#af8334',
    dmc: '680',
    name_color_eng: 'Old Gold — dk',
    name_color_ru: 'Старого золота, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#015731',
    dmc: '699',
    name_color_eng: 'Christmas Green',
    name_color_ru: 'Рождественский зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#2e9148',
    dmc: '700',
    name_color_eng: 'Christmas Green — bright',
    name_color_ru: 'Рождественский зеленый, яркий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#007a3f',
    dmc: '701',
    name_color_eng: 'Christmas Green — lt',
    name_color_ru: 'Рождественский зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#59a052',
    dmc: '702',
    name_color_eng: 'Kelly Green',
    name_color_ru: 'Мутновато-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#81b85e',
    dmc: '703',
    name_color_eng: 'Chartreuse',
    name_color_ru: 'Бледно-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bad765',
    dmc: '704',
    name_color_eng: 'Chartreuse — bright',
    name_color_ru: 'Бледно-зеленый, яркий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e1e1d9',
    dmc: '712',
    name_color_eng: 'Cream',
    name_color_ru: 'Кремовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#9f2d6f',
    dmc: '718',
    name_color_eng: 'Plum',
    name_color_ru: 'Сливовый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#ec6810',
    dmc: '720',
    name_color_eng: 'Orange Spice — dk',
    name_color_ru: 'Красновато-рыжеватый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e4752b',
    dmc: '721',
    name_color_eng: 'Orange Spice — med',
    name_color_ru: 'Красновато-рыжеватый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#faa463',
    dmc: '722',
    name_color_eng: 'Orange Spice — lt',
    name_color_ru: 'Красновато-рыжеватый, св.',
    count: '0',
  },
  { id: crypto.randomUUID(), color: '#fad558', dmc: '725', name_color_eng: 'Topaz', name_color_ru: 'Топаз', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#ffe35f',
    dmc: '726',
    name_color_eng: 'Topaz — lt',
    name_color_ru: 'Топаз, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#feee89',
    dmc: '727',
    name_color_eng: 'Topaz — vy lt',
    name_color_ru: 'Топаз, оч.св.',
    count: '0',
  },
  { id: crypto.randomUUID(), color: '#ecbf3b', dmc: '728', name_color_eng: 'Topaz', name_color_ru: 'Топаз', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#cc993d',
    dmc: '729',
    name_color_eng: 'Old Gold — med',
    name_color_ru: 'Старого золота, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#746d2b',
    dmc: '730',
    name_color_eng: 'Olive Green — vy dk',
    name_color_ru: 'Оливково-зеленый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#837d2f',
    dmc: '731',
    name_color_eng: 'Olive Green — dk',
    name_color_ru: 'Оливково-зеленый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#91852a',
    dmc: '732',
    name_color_eng: 'Olive Green',
    name_color_ru: 'Оливково-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a6a036',
    dmc: '733',
    name_color_eng: 'Olive Green — med',
    name_color_ru: 'Оливково-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d1c66d',
    dmc: '734',
    name_color_eng: 'Olive Green — lt',
    name_color_ru: 'Оливково-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d9c38f',
    dmc: '738',
    name_color_eng: 'Tan — vy lt',
    name_color_ru: 'Желто-коричневый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e5dab2',
    dmc: '739',
    name_color_eng: 'Tan — ultra vy lt',
    name_color_ru: 'Желто-коричневый, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ff7600',
    dmc: '740',
    name_color_eng: 'Tangerine',
    name_color_ru: 'Мандариновый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f69726',
    dmc: '741',
    name_color_eng: 'Tangerine — med',
    name_color_ru: 'Мандариновый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ffc33a',
    dmc: '742',
    name_color_eng: 'Tangerine — lt',
    name_color_ru: 'Мандариновый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ffda5a',
    dmc: '743',
    name_color_eng: 'Yellow — med',
    name_color_ru: 'Желтый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ffe276',
    dmc: '744',
    name_color_eng: 'Yellow — pale',
    name_color_ru: 'Желтый, бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ffeda9',
    dmc: '745',
    name_color_eng: 'Yellow — lt pale',
    name_color_ru: 'Желтый, бледно св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f5f0df',
    dmc: '746',
    name_color_eng: 'Off White',
    name_color_ru: 'Белесый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d3e9e7',
    dmc: '747',
    name_color_eng: 'Sky Blue — vy lt',
    name_color_ru: 'Небесно голубой, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#efc1aa',
    dmc: '754',
    name_color_eng: 'Peach — lt',
    name_color_ru: 'Персиковый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#eac0b4',
    dmc: '758',
    name_color_eng: 'Terra Cotta — vy lt',
    name_color_ru: 'Терракотовый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e29690',
    dmc: '760',
    name_color_eng: 'Salmon',
    name_color_ru: 'Лососевый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f4c4c1',
    dmc: '761',
    name_color_eng: 'Salmon — lt',
    name_color_ru: 'Лососевый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e9e9eb',
    dmc: '762',
    name_color_eng: 'Pearl Grey — vy lt',
    name_color_ru: 'Жемчужно серый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f3f6d4',
    dmc: '772',
    name_color_eng: 'Yellow Green — vy lt',
    name_color_ru: 'Желто-зеленый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ceddea',
    dmc: '775',
    name_color_eng: 'Baby Blue — vy lt',
    name_color_ru: 'Нежно голубой, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#eeaeb0',
    dmc: '776',
    name_color_eng: 'Pink — med',
    name_color_ru: 'Розовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8a373b',
    dmc: '777',
    name_color_eng: 'Raspberry — vy dk',
    name_color_ru: 'Малина оч.т',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ddb3b1',
    dmc: '778',
    name_color_eng: 'Antique Mauve — vy lt',
    name_color_ru: 'Античный розовато-лиловый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6d5748',
    dmc: '779',
    name_color_eng: 'Cocoa — dk',
    name_color_ru: 'Какао т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#936626',
    dmc: '780',
    name_color_eng: 'Topaz — ultra vy dk',
    name_color_ru: 'Топаз, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ba8225',
    dmc: '781',
    name_color_eng: 'Topaz — vy dk',
    name_color_ru: 'Топаз, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b38132',
    dmc: '782',
    name_color_eng: 'Topaz — dk',
    name_color_ru: 'Топаз, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d19d2f',
    dmc: '783',
    name_color_eng: 'Topaz — med',
    name_color_ru: 'Топаз, ср.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#161151',
    dmc: '791',
    name_color_eng: 'Cornflower Blue — vy dk',
    name_color_ru: 'Васильковый, кобальтовый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#7971a0',
    dmc: '792',
    name_color_eng: 'Cornflower Blue — dk',
    name_color_ru: 'Васильковый, кобальтовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#686d8d',
    dmc: '793',
    name_color_eng: 'Cornflower Blue — med',
    name_color_ru: 'Васильковый, кобальтовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8ea7c0',
    dmc: '794',
    name_color_eng: 'Cornflower Blue — lt',
    name_color_ru: 'Васильковый, кобальтовый, св.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#181f66',
    dmc: '796',
    name_color_eng: 'Royal Blue — dk',
    name_color_ru: 'Чисто синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#2c4180',
    dmc: '797',
    name_color_eng: 'Royal Blue',
    name_color_ru: 'Чисто синий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#445997',
    dmc: '798',
    name_color_eng: 'Delft — dk',
    name_color_ru: 'Фарфоровый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6e8db5',
    dmc: '799',
    name_color_eng: 'Delft — med',
    name_color_ru: 'Фарфоровый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c1d3df',
    dmc: '800',
    name_color_eng: 'Delft — pale',
    name_color_ru: 'Фарфоровый, бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#63461f',
    dmc: '801',
    name_color_eng: 'Coffee Brown — dk',
    name_color_ru: 'Кофейный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#437490',
    dmc: '806',
    name_color_eng: 'Peacock Blue — dk',
    name_color_ru: 'Переливчатый синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#70a8b3',
    dmc: '807',
    name_color_eng: 'Peacock Blue',
    name_color_ru: 'Переливчатый синий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6c91c0',
    dmc: '809',
    name_color_eng: 'Delft',
    name_color_ru: 'Фарфоровый',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#91b4ce',
    dmc: '813',
    name_color_eng: 'Blue — lt',
    name_color_ru: 'Синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#711f2e',
    dmc: '814',
    name_color_eng: 'Garnet — dk',
    name_color_ru: 'Гранатовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9d3030',
    dmc: '815',
    name_color_eng: 'Garnet — med',
    name_color_ru: 'Гранатовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#811024',
    dmc: '816',
    name_color_eng: 'Garnet',
    name_color_ru: 'Гранатовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bd2e2e',
    dmc: '817',
    name_color_eng: 'Coral Red — vy dk',
    name_color_ru: 'Кораллово красный, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f9d6dd',
    dmc: '818',
    name_color_eng: 'Baby Pink',
    name_color_ru: 'Нежно розовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fbe2df',
    dmc: '819',
    name_color_eng: 'Baby Pink — lt',
    name_color_ru: 'Нежно розовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#190f60',
    dmc: '820',
    name_color_eng: 'Royal Blue — vy dk',
    name_color_ru: 'Чисто синий, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e2dfd3',
    dmc: '822',
    name_color_eng: 'Beige Grey — lt',
    name_color_ru: 'Бежево-серый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#124477',
    dmc: '823',
    name_color_eng: 'Navy Blue — dk',
    name_color_ru: 'Темно-синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#3b6292',
    dmc: '824',
    name_color_eng: 'Blue — vy dk',
    name_color_ru: 'Синий, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#366390',
    dmc: '825',
    name_color_eng: 'Blue — dk',
    name_color_ru: 'Синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#5a82a2',
    dmc: '826',
    name_color_eng: 'Blue — med',
    name_color_ru: 'Синий, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b4d3e3',
    dmc: '827',
    name_color_eng: 'Blue — vy lt',
    name_color_ru: 'Синий, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#cae2eb',
    dmc: '828',
    name_color_eng: 'Blue — ultra vy lt',
    name_color_ru: 'Синий, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6f5422',
    dmc: '829',
    name_color_eng: 'Golden Olive — vy dk',
    name_color_ru: 'Оливково-золотой, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#806c26',
    dmc: '830',
    name_color_eng: 'Golden Olive — dk',
    name_color_ru: 'Оливково-золотой, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#957b2f',
    dmc: '831',
    name_color_eng: 'Golden Olive — med',
    name_color_ru: 'Оливково-золотой, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b19a3f',
    dmc: '832',
    name_color_eng: 'Golden Olive',
    name_color_ru: 'Оливково-золотой',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bfa43a',
    dmc: '833',
    name_color_eng: 'Golden Olive — lt',
    name_color_ru: 'Оливково-золотой, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#cab751',
    dmc: '834',
    name_color_eng: 'Golden Olive — vy lt',
    name_color_ru: 'Оливково-золотой, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#573c2a',
    dmc: '838',
    name_color_eng: 'Beige Brown — vy dk',
    name_color_ru: 'Бежево-коричневый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#684e37',
    dmc: '839',
    name_color_eng: 'Beige Brown — dk',
    name_color_ru: 'Бежево-коричневый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#977e65',
    dmc: '840',
    name_color_eng: 'Beige Brown — med',
    name_color_ru: 'Бежево-коричневый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b39f8c',
    dmc: '841',
    name_color_eng: 'Beige Brown — lt',
    name_color_ru: 'Бежево-коричневый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#cdb9a4',
    dmc: '842',
    name_color_eng: 'Beige Brown — vy lt',
    name_color_ru: 'Бежево-коричневый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6c6e58',
    dmc: '844',
    name_color_eng: 'Beaver Grey — ultra dk',
    name_color_ru: 'Боброво-серый, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#775820',
    dmc: '869',
    name_color_eng: 'Hazelnut Brown — vy dk',
    name_color_ru: 'Фундука, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#043810',
    dmc: '890',
    name_color_eng: 'Pistachio Green — ultra dk',
    name_color_ru: 'Фисташково зеленый, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ef4949',
    dmc: '891',
    name_color_eng: 'Carnation — dk',
    name_color_ru: 'Гвоздичный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f85b64',
    dmc: '892',
    name_color_eng: 'Carnation — med',
    name_color_ru: 'Гвоздичный, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fc6a84',
    dmc: '893',
    name_color_eng: 'Carnation — lt',
    name_color_ru: 'Гвоздичный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f999a5',
    dmc: '894',
    name_color_eng: 'Carnation — vy lt',
    name_color_ru: 'Гвоздичный, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#29542f',
    dmc: '895',
    name_color_eng: 'Hunter Green — vy dk',
    name_color_ru: 'Защитный, грязновато зеленый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#502f1b',
    dmc: '898',
    name_color_eng: 'Coffee Brown — vy dk',
    name_color_ru: 'Кофейный, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ee8593',
    dmc: '899',
    name_color_eng: 'Rose — med',
    name_color_ru: 'Розы, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d45d28',
    dmc: '900',
    name_color_eng: 'Burnt Orange — dk',
    name_color_ru: 'Оранжево-жженный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6b3b33',
    dmc: '902',
    name_color_eng: 'Garnet — vy dk',
    name_color_ru: 'Гранатовый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4f6c33',
    dmc: '904',
    name_color_eng: 'Parrot Green — vy dk',
    name_color_ru: 'Зеленый попугаевый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#759a3e',
    dmc: '905',
    name_color_eng: 'Parrot Green — dk',
    name_color_ru: 'Зеленый попугаевый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#82ae44',
    dmc: '906',
    name_color_eng: 'Parrot Green — med',
    name_color_ru: 'Зеленый попугаевый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a9c33e',
    dmc: '907',
    name_color_eng: 'Parrot Green — lt',
    name_color_ru: 'Зеленый попугаевый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#00793b',
    dmc: '909',
    name_color_eng: 'Emerald Green — vy dk',
    name_color_ru: 'Изумрудный, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#008c4c',
    dmc: '910',
    name_color_eng: 'Emerald Green — dk',
    name_color_ru: 'Изумрудный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#40a756',
    dmc: '911',
    name_color_eng: 'Emerald Green — med',
    name_color_ru: 'Изумрудный, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#58a96b',
    dmc: '912',
    name_color_eng: 'Emerald Green — lt',
    name_color_ru: 'Изумрудный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#88c78d',
    dmc: '913',
    name_color_eng: 'Nile Green — med',
    name_color_ru: 'Мутно-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#800137',
    dmc: '915',
    name_color_eng: 'Plum — dk',
    name_color_ru: 'Сливовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#832a58',
    dmc: '917',
    name_color_eng: 'Plum — med',
    name_color_ru: 'Сливовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8c3b1a',
    dmc: '918',
    name_color_eng: 'Red Copper — dk',
    name_color_ru: 'Красной меди, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9b3b1b',
    dmc: '919',
    name_color_eng: 'Red Copper',
    name_color_ru: 'Красной меди',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a74f2a',
    dmc: '920',
    name_color_eng: 'Copper — med',
    name_color_ru: 'Медный, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c36b29',
    dmc: '921',
    name_color_eng: 'Copper',
    name_color_ru: 'Медный',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#d6834d',
    dmc: '922',
    name_color_eng: 'Copper — lt',
    name_color_ru: 'Медный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#42605c',
    dmc: '924',
    name_color_eng: 'Grey Green — vy dk',
    name_color_ru: 'Серо-зеленый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#789899',
    dmc: '926',
    name_color_eng: 'Grey Green — med',
    name_color_ru: 'Серо-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c5d2cf',
    dmc: '927',
    name_color_eng: 'Grey Green — lt',
    name_color_ru: 'Серо-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e5eae9',
    dmc: '928',
    name_color_eng: 'Grey Green — vy lt',
    name_color_ru: 'Серо-зеленый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#435e67',
    dmc: '930',
    name_color_eng: 'Antique Blue — dk',
    name_color_ru: 'Античный синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#678997',
    dmc: '931',
    name_color_eng: 'Antique Blue — med',
    name_color_ru: 'Античный синий, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8faeb9',
    dmc: '932',
    name_color_eng: 'Antique Blue — lt',
    name_color_ru: 'Античный синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4d4c34',
    dmc: '934',
    name_color_eng: 'Black Avocado Green — dk',
    name_color_ru: 'Черно-зеленого авокадо, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4b5035',
    dmc: '935',
    name_color_eng: 'Black Avocado Green — med',
    name_color_ru: 'Черно-зеленого авокадо, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#5d5c2b',
    dmc: '936',
    name_color_eng: 'Avocado Green — vy dk',
    name_color_ru: 'Авокадо, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4f5925',
    dmc: '937',
    name_color_eng: 'Avocado Green — med',
    name_color_ru: 'Авокадо, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#3b2811',
    dmc: '938',
    name_color_eng: 'Coffee Brown — ultra dk',
    name_color_ru: 'Кофейный, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#02101c',
    dmc: '939',
    name_color_eng: 'Navy Blue — vy dk',
    name_color_ru: 'Темно-синий, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#009a7b',
    dmc: '943',
    name_color_eng: 'Aquamarine — med',
    name_color_ru: 'Аквамарин, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e3be8e',
    dmc: '945',
    name_color_eng: 'Tawny',
    name_color_ru: 'Рыжевато-коричневый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e15729',
    dmc: '946',
    name_color_eng: 'Burnt Orange — med',
    name_color_ru: 'Оранжево-жженный, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f26922',
    dmc: '947',
    name_color_eng: 'Burnt Orange',
    name_color_ru: 'Оранжево-жженный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#feebe2',
    dmc: '948',
    name_color_eng: 'Peach — vy lt',
    name_color_ru: 'Персиковый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e7ceb9',
    dmc: '950',
    name_color_eng: 'Desert Sand — lt',
    name_color_ru: 'Пустынного песка, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f2e0ce',
    dmc: '951',
    name_color_eng: 'Tawny — lt',
    name_color_ru: 'Рыжевато-коричневый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#abd58b',
    dmc: '954',
    name_color_eng: 'Nile Green',
    name_color_ru: 'Мутно-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b4e8b3',
    dmc: '955',
    name_color_eng: 'Nile Green — lt',
    name_color_ru: 'Мутно-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ff7a90',
    dmc: '956',
    name_color_eng: 'Geranium',
    name_color_ru: 'Герань',
    count: 0,
  },
  {
    id: crypto.randomUUID(),
    color: '#f9afb7',
    dmc: '957',
    name_color_eng: 'Geranium — pale',
    name_color_ru: 'Герань, бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#51c0bb',
    dmc: '958',
    name_color_eng: 'Seagreen — dk',
    name_color_ru: 'Морской воды, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8fd3d4',
    dmc: '959',
    name_color_eng: 'Seagreen — med',
    name_color_ru: 'Морской воды, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#df6877',
    dmc: '961',
    name_color_eng: 'Dusty Rose — dk',
    name_color_ru: 'Пыльной розы, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f08d9f',
    dmc: '962',
    name_color_eng: 'Dusty Rose — med',
    name_color_ru: 'Пыльной розы, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fad0d5',
    dmc: '963',
    name_color_eng: 'Dusty Rose — ultra vy lt',
    name_color_ru: 'Пыльной розы, очень св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9cd3cc',
    dmc: '964',
    name_color_eng: 'Seagreen — lt',
    name_color_ru: 'Морской воды, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bbd7ae',
    dmc: '966',
    name_color_eng: 'Baby Green — med',
    name_color_ru: 'Нежно зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fbdbcd',
    dmc: '967',
    name_color_eng: 'Apricot — vy lt',
    name_color_ru: 'Абрикосовый оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ff781e',
    dmc: '970',
    name_color_eng: 'Pumpkin — bright',
    name_color_ru: 'Тыквенный, яркий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fc7e0c',
    dmc: '971',
    name_color_eng: 'Pumpkin',
    name_color_ru: 'Тыквенный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ffb401',
    dmc: '972',
    name_color_eng: 'Canary — deep',
    name_color_ru: 'Канареечный, глубокий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ffe21a',
    dmc: '973',
    name_color_eng: 'Canary — bright',
    name_color_ru: 'Канареечный, яркий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#945c2d',
    dmc: '975',
    name_color_eng: 'Golden Brown — dk',
    name_color_ru: 'Золотисто-коричневый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e6973f',
    dmc: '976',
    name_color_eng: 'Golden Brown — med',
    name_color_ru: 'Золотисто-коричневый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e59034',
    dmc: '977',
    name_color_eng: 'Golden Brown — lt',
    name_color_ru: 'Золотисто-коричневый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#1f561f',
    dmc: '986',
    name_color_eng: 'Forest Green — vy dk',
    name_color_ru: 'Зеленый лесной, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#568357',
    dmc: '987',
    name_color_eng: 'Forest Green — dk',
    name_color_ru: 'Зеленый лесной, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#76996c',
    dmc: '988',
    name_color_eng: 'Forest Green — med',
    name_color_ru: 'Зеленый лесной, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#87a462',
    dmc: '989',
    name_color_eng: 'Forest Green',
    name_color_ru: 'Зеленый лесной',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#176a59',
    dmc: '991',
    name_color_eng: 'Aquamarine — dk',
    name_color_ru: 'Аквамарин, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6cbfa8',
    dmc: '992',
    name_color_eng: 'Aquamarine — lt',
    name_color_ru: 'Аквамарин, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8ec2b3',
    dmc: '993',
    name_color_eng: 'Aquamarine — vy lt',
    name_color_ru: 'Аквамарин, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#0064b0',
    dmc: '995',
    name_color_eng: 'Electric Blue — dk',
    name_color_ru: 'Электрик синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#57baf5',
    dmc: '996',
    name_color_eng: 'Electric Blue — med',
    name_color_ru: 'Электрик синий, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#635f2f',
    dmc: '3011',
    name_color_eng: 'Khaki Green — dk',
    name_color_ru: 'Хаки, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9b9648',
    dmc: '3012',
    name_color_eng: 'Khaki Green — med',
    name_color_ru: 'Хаки, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#999c6c',
    dmc: '3013',
    name_color_eng: 'Khaki Green — lt',
    name_color_ru: 'Хаки, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#3b2e08',
    dmc: '3021',
    name_color_eng: 'Brown Grey — vy dk',
    name_color_ru: 'Коричнево-серый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#938e6e',
    dmc: '3022',
    name_color_eng: 'Brown Grey — med',
    name_color_ru: 'Коричнево-серый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b2ae95',
    dmc: '3023',
    name_color_eng: 'Brown Grey — lt',
    name_color_ru: 'Коричнево-серый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#dcdcd7',
    dmc: '3024',
    name_color_eng: 'Brown Grey — vy lt',
    name_color_ru: 'Коричнево-серый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#442e10',
    dmc: '3031',
    name_color_eng: 'Mocha Brown — vy dk',
    name_color_ru: 'Мокка, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ada183',
    dmc: '3032',
    name_color_eng: 'Mocha Brown — med',
    name_color_ru: 'Мокка, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d7d0c2',
    dmc: '3033',
    name_color_eng: 'Mocha Brown — vy lt',
    name_color_ru: 'Мокка, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#966e6e',
    dmc: '3041',
    name_color_eng: 'Antique Violet — med',
    name_color_ru: 'Антично фиолетовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ccc1d0',
    dmc: '3042',
    name_color_eng: 'Antique Violet — lt',
    name_color_ru: 'Антично фиолетовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b19563',
    dmc: '3045',
    name_color_eng: 'Yellow Beige — dk',
    name_color_ru: 'Желтовато-бежевый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ccbc7d',
    dmc: '3046',
    name_color_eng: 'Yellow Beige — med',
    name_color_ru: 'Желтовато-бежевый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ececd2',
    dmc: '3047',
    name_color_eng: 'Yellow Beige — lt',
    name_color_ru: 'Желтовато-бежевый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6d6f42',
    dmc: '3051',
    name_color_eng: 'Green Grey — dk',
    name_color_ru: 'Серо-зеленый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#899770',
    dmc: '3052',
    name_color_eng: 'Green Grey — med',
    name_color_ru: 'Серо-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bac28b',
    dmc: '3053',
    name_color_eng: 'Green Grey',
    name_color_ru: 'Серо-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#cda072',
    dmc: '3064',
    name_color_eng: 'Desert Sand',
    name_color_ru: 'Пустынного песка',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e3e6dc',
    dmc: '3072',
    name_color_eng: 'Beaver Grey — vy lt',
    name_color_ru: 'Боброво-серый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fff3ad',
    dmc: '3078',
    name_color_eng: 'Golden Yellow — vy lt',
    name_color_ru: 'Желтый золотой, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c6d3e1',
    dmc: '3325',
    name_color_eng: 'Baby Blue — lt',
    name_color_ru: 'Нежно голубой, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f7b4b7',
    dmc: '3326',
    name_color_eng: 'Rose — lt',
    name_color_ru: 'Розы, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c36154',
    dmc: '3328',
    name_color_eng: 'Salmon — dk',
    name_color_ru: 'Лососевый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f38351',
    dmc: '3340',
    name_color_eng: 'Apricot — med',
    name_color_ru: 'Абрикосовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fbbe9d',
    dmc: '3341',
    name_color_eng: 'Apricot',
    name_color_ru: 'Абрикосовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#486131',
    dmc: '3345',
    name_color_eng: 'Hunter Green — dk',
    name_color_ru: 'Защитный, грязновато зеленый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6a823d',
    dmc: '3346',
    name_color_eng: 'Hunter Green',
    name_color_ru: 'Защитный, грязновато зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#78983b',
    dmc: '3347',
    name_color_eng: 'Yellow Green — med',
    name_color_ru: 'Желто-зеленый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e3ee9f',
    dmc: '3348',
    name_color_eng: 'Yellow Green — lt',
    name_color_ru: 'Желто-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b95569',
    dmc: '3350',
    name_color_eng: 'Dusty Rose — ultra dk',
    name_color_ru: 'Пыльной розы, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e3a5aa',
    dmc: '3354',
    name_color_eng: 'Dusty Rose — lt',
    name_color_ru: 'Пыльной розы, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#2e3d1a',
    dmc: '3362',
    name_color_eng: 'Pine Green — dk',
    name_color_ru: 'Сосновый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#72885f',
    dmc: '3363',
    name_color_eng: 'Pine Green — med',
    name_color_ru: 'Сосновый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#85905c',
    dmc: '3364',
    name_color_eng: 'Pine Green',
    name_color_ru: 'Сосновый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#2d1705',
    dmc: '3371',
    name_color_eng: 'Black Brown',
    name_color_ru: 'Черно-коричневый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b34e8c',
    dmc: '3607',
    name_color_eng: 'Plum — lt',
    name_color_ru: 'Сливовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c07ba3',
    dmc: '3608',
    name_color_eng: 'Plum — vy lt',
    name_color_ru: 'Сливовый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e9afd3',
    dmc: '3609',
    name_color_eng: 'Plum — ultra lt',
    name_color_ru: 'Сливовый, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#7d3248',
    dmc: '3685',
    name_color_eng: 'Mauve — vy dk',
    name_color_ru: 'Розовато-лиловый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c2596d',
    dmc: '3687',
    name_color_eng: 'Mauve',
    name_color_ru: 'Розовато-лиловый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e6849a',
    dmc: '3688',
    name_color_eng: 'Mauve — med',
    name_color_ru: 'Розовато-лиловый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e8b9c5',
    dmc: '3689',
    name_color_eng: 'Mauve — lt',
    name_color_ru: 'Розовато-лиловый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f65d5b',
    dmc: '3705',
    name_color_eng: 'Melon — dk',
    name_color_ru: 'Дыни, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ff988e',
    dmc: '3706',
    name_color_eng: 'Melon — med',
    name_color_ru: 'Дыни, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fcbbc1',
    dmc: '3708',
    name_color_eng: 'Melon — lt',
    name_color_ru: 'Дыни, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#db7d73',
    dmc: '3712',
    name_color_eng: 'Salmon — med',
    name_color_ru: 'Лососевый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fcdcda',
    dmc: '3713',
    name_color_eng: 'Salmon — vy lt',
    name_color_ru: 'Лососевый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fcb1ba',
    dmc: '3716',
    name_color_eng: 'Dusty Rose — vy lt',
    name_color_ru: 'Пыльной розы, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#aa5048',
    dmc: '3721',
    name_color_eng: 'Shell Pink — dk',
    name_color_ru: 'Розовых ракушек, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a45d55',
    dmc: '3722',
    name_color_eng: 'Shell Pink — med',
    name_color_ru: 'Розовых ракушек, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#874c49',
    dmc: '3726',
    name_color_eng: 'Antique Mauve — dk',
    name_color_ru: 'Античный розовато-лиловый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e6bcc3',
    dmc: '3727',
    name_color_eng: 'Antique Mauve — lt',
    name_color_ru: 'Античный розовато-лиловый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c65a6b',
    dmc: '3731',
    name_color_eng: 'Dusty Rose — vy dk',
    name_color_ru: 'Пыльной розы, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#eda6ac',
    dmc: '3733',
    name_color_eng: 'Dusty Rose',
    name_color_ru: 'Пыльной розы',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#72535a',
    dmc: '3740',
    name_color_eng: 'Antique Violet — dk',
    name_color_ru: 'Антично фиолетовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c7bac7',
    dmc: '3743',
    name_color_eng: 'Antique Violet — vy lt',
    name_color_ru: 'Антично фиолетовый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8572a4',
    dmc: '3746',
    name_color_eng: 'Blue Violet — dk',
    name_color_ru: 'Сине-фиолетовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bcc0d8',
    dmc: '3747',
    name_color_eng: 'Blue Violet — vy lt',
    name_color_ru: 'Сине-фиолетовый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#444d58',
    dmc: '3750',
    name_color_eng: 'Antique Blue — vy dk',
    name_color_ru: 'Античный синий, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#bbc8d6',
    dmc: '3752',
    name_color_eng: 'Antique Blue — vy lt',
    name_color_ru: 'Античный синий, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ccd5da',
    dmc: '3753',
    name_color_eng: 'Antique Blue — ultra vy lt',
    name_color_ru: 'Античный синий, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#9fbbd5',
    dmc: '3755',
    name_color_eng: 'Baby Blue',
    name_color_ru: 'Нежно голубой',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e8edf3',
    dmc: '3756',
    name_color_eng: 'Baby Blue — ultra vy lt',
    name_color_ru: 'Нежно голубой, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4f819d',
    dmc: '3760',
    name_color_eng: 'Wedgwood — med',
    name_color_ru: 'Пыльно-синий, ср. (гжель)',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b8dae9',
    dmc: '3761',
    name_color_eng: 'Sky Blue — lt',
    name_color_ru: 'Небесно голубой, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#296e87',
    dmc: '3765',
    name_color_eng: 'Peacock Blue — vy dk',
    name_color_ru: 'Переливчатый синий, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#7cbec6',
    dmc: '3766',
    name_color_eng: 'Peacock Blue — lt',
    name_color_ru: 'Переливчатый синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6b8084',
    dmc: '3768',
    name_color_eng: 'Grey Green — dk',
    name_color_ru: 'Серо-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f8eedc',
    dmc: '3770',
    name_color_eng: 'Tawny — vy lt',
    name_color_ru: 'Рыжевато-коричневый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e8b58f',
    dmc: '3771',
    name_color_eng: 'Terra Cotta — ultra vy lt',
    name_color_ru: 'Терракотовый, ультра оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b8846c',
    dmc: '3772',
    name_color_eng: 'Desert Sand — vy dk',
    name_color_ru: 'Пустынного песка, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d8b39d',
    dmc: '3773',
    name_color_eng: 'Desert Sand — med',
    name_color_ru: 'Пустынного песка, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f6e1d0',
    dmc: '3774',
    name_color_eng: 'Desert Sand — vy lt',
    name_color_ru: 'Пустынного песка, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c27d45',
    dmc: '3776',
    name_color_eng: 'Mahogany — lt',
    name_color_ru: 'Красного дерева, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#892b21',
    dmc: '3777',
    name_color_eng: 'Terra Cotta — vy dk',
    name_color_ru: 'Терракотовый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c4856f',
    dmc: '3778',
    name_color_eng: 'Terra Cotta — lt',
    name_color_ru: 'Терракотовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f2c6b8',
    dmc: '3779',
    name_color_eng: 'Terra Cotta — ultra vy lt',
    name_color_ru: 'Терракотовый, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#5c4c2d',
    dmc: '3781',
    name_color_eng: 'Mocha Brown — dk',
    name_color_ru: 'Мокка, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d2caba',
    dmc: '3782',
    name_color_eng: 'Mocha Brown — lt',
    name_color_ru: 'Мокка, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#605b45',
    dmc: '3787',
    name_color_eng: 'Brown Grey — dk',
    name_color_ru: 'Коричнево-серый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#978266',
    dmc: '3790',
    name_color_eng: 'Beige Grey — ultra dk',
    name_color_ru: 'Бежево-серый, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#2f3b36',
    dmc: '3799',
    name_color_eng: 'Pewter Grey — vy dk',
    name_color_ru: 'Оловянно серый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e65952',
    dmc: '3801',
    name_color_eng: 'Christmas Red — lt',
    name_color_ru: 'Рождественский красный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6f2e35',
    dmc: '3802',
    name_color_eng: 'Antique Mauve — vy dk',
    name_color_ru: 'Античный розовато-лиловый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#863248',
    dmc: '3803',
    name_color_eng: 'Mauve — dk',
    name_color_ru: 'Розовато-лиловый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c33c62',
    dmc: '3804',
    name_color_eng: 'Cyclamen Pink — dk',
    name_color_ru: 'Розового цикламена, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ce507f',
    dmc: '3805',
    name_color_eng: 'Cyclamen Pink',
    name_color_ru: 'Розового цикламена',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f19ac2',
    dmc: '3806',
    name_color_eng: 'Cyclamen Pink — lt',
    name_color_ru: 'Розового цикламена, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#073563',
    dmc: '3807',
    name_color_eng: 'Cornflower Blue',
    name_color_ru: 'Васильковый, кобальтовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#0c464b',
    dmc: '3808',
    name_color_eng: 'Turquoise — ultra vy dk',
    name_color_ru: 'Бирюзовый, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#1c869b',
    dmc: '3809',
    name_color_eng: 'Turquoise — vy dk',
    name_color_ru: 'Бирюзовый, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#4fa1a9',
    dmc: '3810',
    name_color_eng: 'Turquoise — dk',
    name_color_ru: 'Бирюзовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c4e7e8',
    dmc: '3811',
    name_color_eng: 'Turquoise — vy lt',
    name_color_ru: 'Бирюзовый, оч.св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#008679',
    dmc: '3812',
    name_color_eng: 'Seagreen — vy dk',
    name_color_ru: 'Морской воды, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b8cebe',
    dmc: '3813',
    name_color_eng: 'Blue Green — lt',
    name_color_ru: 'Сине-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#3f8878',
    dmc: '3814',
    name_color_eng: 'Aquamarine',
    name_color_ru: 'Аквамарин',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#538a6d',
    dmc: '3815',
    name_color_eng: 'Celadon Green — dk',
    name_color_ru: 'Серовато-зеленый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#699d85',
    dmc: '3816',
    name_color_eng: 'Celadon Green',
    name_color_ru: 'Серовато-зеленый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a6c5b4',
    dmc: '3817',
    name_color_eng: 'Celadon Green — lt',
    name_color_ru: 'Серовато-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#005d2e',
    dmc: '3818',
    name_color_eng: 'Emerald Green — ultra vy dk',
    name_color_ru: 'Изумрудный, ультра т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#d2d057',
    dmc: '3819',
    name_color_eng: 'Moss Green — lt',
    name_color_ru: 'Мох, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ddb442',
    dmc: '3820',
    name_color_eng: 'Straw — dk',
    name_color_ru: 'Соломенный, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e2b73a',
    dmc: '3821',
    name_color_eng: 'Straw',
    name_color_ru: 'Соломенный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f1d863',
    dmc: '3822',
    name_color_eng: 'Straw — lt',
    name_color_ru: 'Соломенный, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fffcdc',
    dmc: '3823',
    name_color_eng: 'Yellow — ultra pale',
    name_color_ru: 'Желтый, ультра бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fbccb8',
    dmc: '3824',
    name_color_eng: 'Apricot — lt',
    name_color_ru: 'Абрикосовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fdc391',
    dmc: '3825',
    name_color_eng: 'Pumpkin — pale',
    name_color_ru: 'Тыквенный, бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c38c55',
    dmc: '3826',
    name_color_eng: 'Golden Brown',
    name_color_ru: 'Золотовато-коричневый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e8aa5f',
    dmc: '3827',
    name_color_eng: 'Golden Brown — pale',
    name_color_ru: 'Золотовато-коричневый, бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#af8846',
    dmc: '3828',
    name_color_eng: 'Hazelnut Brown',
    name_color_ru: 'Фундука',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a47829',
    dmc: '3829',
    name_color_eng: 'Old Gold — vy dk',
    name_color_ru: 'Старого золота, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b97161',
    dmc: '3830',
    name_color_eng: 'Terra Cotta',
    name_color_ru: 'Терракотовый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b33034',
    dmc: '3831',
    name_color_eng: 'Raspberry — dk',
    name_color_ru: 'Малиновый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b33034',
    dmc: '3832',
    name_color_eng: 'Raspberry — med',
    name_color_ru: 'Малиновый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e8868c',
    dmc: '3833',
    name_color_eng: 'Raspberry — lt',
    name_color_ru: 'Малиновый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#642441',
    dmc: '3834',
    name_color_eng: 'Grape — dk',
    name_color_ru: 'Красного винограда, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#784775',
    dmc: '3835',
    name_color_eng: 'Grape — med',
    name_color_ru: 'Красного винограда, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c1aec2',
    dmc: '3836',
    name_color_eng: 'Grape — lt',
    name_color_ru: 'Красного винограда, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#7c4087',
    dmc: '3837',
    name_color_eng: 'Lavender — ultra dk',
    name_color_ru: 'Лаванда, ультра тёмный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#62669a',
    dmc: '3838',
    name_color_eng: 'Lavender Blue — dk',
    name_color_ru: 'Лавандово-синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#94a8c9',
    dmc: '3839',
    name_color_eng: 'Lavender Blue — med',
    name_color_ru: 'Лавандово-синий, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c1d4ec',
    dmc: '3840',
    name_color_eng: 'Lavender Blue — lt',
    name_color_ru: 'Лавандово-синий, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#cbdde7',
    dmc: '3841',
    name_color_eng: 'Baby Blue — pale',
    name_color_ru: 'Нежно голубой, бледный',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#12557e',
    dmc: '3842',
    name_color_eng: 'Wedgwood — dk',
    name_color_ru: 'Пыльно-синий, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#0095d3',
    dmc: '3843',
    name_color_eng: 'Electric Blue',
    name_color_ru: 'Волнующе синий',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#0095d3',
    dmc: '3844',
    name_color_eng: 'Bright Turquoise — dk',
    name_color_ru: 'Ярко-бирюзовый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#01cbec',
    dmc: '3845',
    name_color_eng: 'Bright Turquoise — med',
    name_color_ru: 'Ярко-бирюзовый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#63d3e1',
    dmc: '3846',
    name_color_eng: 'Bright Turquoise — lt',
    name_color_ru: 'Ярко-бирюзовый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#00604e',
    dmc: '3847',
    name_color_eng: 'Teal Green — dk',
    name_color_ru: 'Цвет рабочего стола Windows, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#42917f',
    dmc: '3848',
    name_color_eng: 'Teal Green — med',
    name_color_ru: 'Цвет рабочего стола Windows, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#6eb2a7',
    dmc: '3849',
    name_color_eng: 'Teal Green — lt',
    name_color_ru: 'Цвет рабочего стола Windows, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#08926f',
    dmc: '3850',
    name_color_eng: 'Bright Green — dk',
    name_color_ru: 'Ярко-зеленый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#56b69c',
    dmc: '3851',
    name_color_eng: 'Bright Green — lt',
    name_color_ru: 'Ярко-зеленый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#cc972b',
    dmc: '3852',
    name_color_eng: 'Straw — vy dk',
    name_color_ru: 'Соломенный, оч.т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#fc9749',
    dmc: '3853',
    name_color_eng: 'Autumn Gold — dk',
    name_color_ru: 'Золотой осенний, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f7b25c',
    dmc: '3854',
    name_color_eng: 'Autumn Gold — med',
    name_color_ru: 'Золотой осенний, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#f7ca84',
    dmc: '3855',
    name_color_eng: 'Autumn Gold — lt',
    name_color_ru: 'Золотой осенний, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#ebbc9a',
    dmc: '3856',
    name_color_eng: 'Mahogany — ultra vy lt',
    name_color_ru: 'Красного дерева, ультра св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#804133',
    dmc: '3857',
    name_color_eng: 'Rosewood — dk',
    name_color_ru: 'Розового дерева, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#8d5745',
    dmc: '3858',
    name_color_eng: 'Rosewood — med',
    name_color_ru: 'Розового дерева, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#b68472',
    dmc: '3859',
    name_color_eng: 'Rosewood — lt',
    name_color_ru: 'Розового дерева, св.',
    count: '0',
  },
  { id: crypto.randomUUID(), color: '#947974', dmc: '3860', name_color_eng: 'Cocoa', name_color_ru: 'Какао', count: 0 },
  {
    id: crypto.randomUUID(),
    color: '#9e887f',
    dmc: '3861',
    name_color_eng: 'Cocoa — lt',
    name_color_ru: 'Какао, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#845f2e',
    dmc: '3862',
    name_color_eng: 'Mocha Beige — dk',
    name_color_ru: 'Темно-коричневый бежевый, т.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#a4866c',
    dmc: '3863',
    name_color_eng: 'Mocha Beige — med',
    name_color_ru: 'Темно-коричневый бежевый, ср.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#c9af93',
    dmc: '3864',
    name_color_eng: 'Mocha Beige — lt',
    name_color_ru: 'Темно-коричневый бежевый, св.',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#faf9f5',
    dmc: '3865',
    name_color_eng: 'Winter White',
    name_color_ru: 'Снежно белый',
    count: '0',
  },
  {
    id: crypto.randomUUID(),
    color: '#e7e5dd',
    dmc: '3866',
    name_color_eng: 'Mocha Brown — ultra vy lt',
    name_color_ru: 'Мокка, ультра св.',
    count: '0',
  },
];
